- path: Albert Henckels.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Author.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Clotilde.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Deputy Vilmos Kovacs.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Dmitri Desgoffe-und-Taxis.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Dowager Countess Céline Villeneuve Desgoffe-und-Taxis.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Elderly Zero.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Herr Mendl.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: J.G. Jopling.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Ludwig.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: M. Chuck.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: M. Ivan.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 324
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: M. Jean.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 648
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Monsieur Gustave H..jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 972
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Serge X..jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Young Author.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 1620
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Zero Moustafa.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=11877b0a
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
