- path: Doctor Who, Season 18.jpg
  width: 1080
  height: 1620
  thumb: thumbnails_0.jpg?crc=4246322f
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1335
  thumb_total_height: 324
- path: Saturday Night Live, Season 6.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=4246322f
  thumb_x: 216
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 1335
  thumb_total_height: 324
- path: Sesame Street, Season 12.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=4246322f
  thumb_x: 459
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1335
  thumb_total_height: 324
- path: The Jeffersons, Season 7.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=4246322f
  thumb_x: 675
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1335
  thumb_total_height: 324
- path: The Muppet Show, Season 5.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=4246322f
  thumb_x: 895
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1335
  thumb_total_height: 324
- path: Cosmos.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=4246322f
  thumb_x: 1115
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1335
  thumb_total_height: 324
