- path: La La Land.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: 10 Cloverfield Lane.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: 20th Century Women.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: A Silent Voice The Movie.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Arrival.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Batman v Superman Dawn of Justice.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Captain America Civil War.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Deadpool.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Doctor Strange.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Everybody Wants Some!!.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Ghostbusters.jpg
  width: 800
  height: 1201
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Hacksaw Ridge.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Hell or High Water.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Hidden Figures.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Hunt for the Wilderpeople.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Ice Age Collision Course.jpg
  width: 800
  height: 1201
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Jason Bourne.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Kung Fu Panda 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Manchester by the Sea.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1728
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Moana.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Moonlight.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Nocturnal Animals.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: O.J.jpg
  width: 680
  height: 1015
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 432
  thumb_y: 648
  thumb_width: 217
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Paterson.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 649
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Popstar Never Stop Never Stopping.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 865
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Pride and Prejudice and Zombies.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1081
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Raw.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1297
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Resident Evil The Final Chapter.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1513
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Rogue One A Star Wars Story.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1729
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Shin Godzilla.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1945
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Silence.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Sing Street.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 216
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Suicide Squad.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 432
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: The Conjuring 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 648
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: The Handmaiden.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 864
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: The Jungle Book.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1080
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: The Nice Guys.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1296
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: The Purge Election Year.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1512
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: The Wailing.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1728
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Toni Erdmann.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 1944
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Train to Busan.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Warcraft.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 216
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: X-Men Apocalypse.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 432
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
- path: Your Name.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5984f7bd
  thumb_x: 648
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2161
  thumb_total_height: 1620
