- path: Augustine Salazar.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Clarence "Da" Shi.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Dr. Ye Wenjie.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Follower.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Jack Rooney.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Jin Cheng.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Mike Evans.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Raj Varma.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Saul Durand.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Shao Lin.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Sophon.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Tang Hongjing.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 324
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Tatiana.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 648
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Thomas Wade.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 972
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Vera Ye.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Will Downing.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 1620
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Ye Wenjie (young).jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Ye Zhetai.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6f983fd1
  thumb_x: 2268
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
