- path: Halloween The Curse of Michael Myers.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=ff962bf3
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: Judge Dredd.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=ff962bf3
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: Mortal Kombat.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=ff962bf3
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: Rob Roy.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=ff962bf3
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
