- path: Mad Men, Season 7.jpg
  width: 800
  height: 1199
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: The Americans, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: True Detective.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Brooklyn Nine-Nine, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Community, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Modern Family, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: All Hail King Julien.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Fargo.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Game of Thrones, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Marco Polo.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1944
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Rectify, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: One Piece, Season 17.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: 24, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: CSI Crime Scene Investigation, Season 15.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Criminal Minds, Season 10.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Grey's Anatomy, Season 11.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Homeland, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: NCIS, Season 12.jpg
  width: 800
  height: 1124
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 230
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Adventure Time, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1742
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Archer, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1958
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: BoJack Horseman.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Bob's Burgers, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Family Guy, Season 13.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Gravity Falls, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Regular Show, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 864
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: South Park, Season 18.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1080
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: The Simpsons, Season 26.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1296
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Halt and Catch Fire.jpg
  width: 544
  height: 800
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1512
  thumb_y: 648
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Orphan Black, Season 2.jpg
  width: 553
  height: 800
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1732
  thumb_y: 648
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: The Leftovers.jpg
  width: 554
  height: 800
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1956
  thumb_y: 648
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Doctor Who, Season 8.jpg
  width: 800
  height: 1134
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_y: 972
  thumb_width: 228
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Downton Abbey, Season 5.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 228
  thumb_y: 972
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Orange Is the New Black, Season 2.jpg
  width: 300
  height: 433
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 448
  thumb_y: 972
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Saturday Night Live, Season 40.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 672
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: The Good Wife, Season 6.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 915
  thumb_y: 972
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
- path: Veep, Season 3.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=5853a83
  thumb_x: 1135
  thumb_y: 972
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2180
  thumb_total_height: 1296
