- path: Lethal weapon.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=25a1e39f
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1512
  thumb_total_height: 324
- path: Predator.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=25a1e39f
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1512
  thumb_total_height: 324
- path: Robocop.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=25a1e39f
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1512
  thumb_total_height: 324
- path: The Gate.jpg
  width: 800
  height: 1201
  thumb: thumbnails_0.jpg?crc=25a1e39f
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1512
  thumb_total_height: 324
- path: A Nightmare on Elm Street 3 Dream Warriors.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=25a1e39f
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1512
  thumb_total_height: 324
- path: Beverly Hills Cop II.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=25a1e39f
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1512
  thumb_total_height: 324
- path: The Living Daylights.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=25a1e39f
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1512
  thumb_total_height: 324
