- path: Harry Potter and the Philosopher's Stone.jpeg
  width: 1000
  height: 1500
  thumb: thumbnails_0.jpg?crc=3058b33e
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 432
  thumb_total_height: 324
- path: Amélie.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3058b33e
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 432
  thumb_total_height: 324
