- path: Harry Potter and the Philosopher's Stone.jpeg
  width: 1000
  height: 1500
  thumb: thumbnails_0.jpg?crc=ec9c75c8
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 216
  thumb_total_height: 324
