- path: Alien Trilogy.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=3fe60641
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Broken Sword The Shadow of the Templars.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=3fe60641
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Command & Conquer Red Alert.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=3fe60641
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Command & Conquer The Covert Operations.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=3fe60641
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Quake.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=3fe60641
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Resident Evil.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=3fe60641
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: The Elder Scrolls II Daggerfall.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=3fe60641
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: The Settlers II Veni, Vidi, Vici.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=3fe60641
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Tomb Raider.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=3fe60641
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Warcraft II Beyond the Dark Portal.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=3fe60641
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Worms Reinforcements.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=3fe60641
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
