- path: Silo, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: The Boys, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: The Pitt, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: Jujutsu Kaisen, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: One Piece, Season 23.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: For All Mankind, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: Criminal Minds, Season 19.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: Family Guy, Season 24.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: House of the Dragon, Season 3.jpg
  width: 1080
  height: 1350
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_x: 1728
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: Sesame Street, Season 56.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_x: 1987
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: American Idol, Season 24.jpg
  width: 800
  height: 1422
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_y: 324
  thumb_width: 182
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: Big Brother, Season 28.jpg
  width: 800
  height: 1158
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_x: 182
  thumb_y: 324
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: Project Runway, Season 22.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_x: 406
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: Survivor, Season 50.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_x: 649
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
- path: Top Chef, Season 23.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e537a43
  thumb_x: 892
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 648
