- path: Silo, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4dafdd95
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 324
- path: The Boys, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4dafdd95
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 324
- path: The Pitt, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4dafdd95
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 324
- path: Jujutsu Kaisen, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4dafdd95
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 324
- path: One Piece, Season 23.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4dafdd95
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 324
- path: For All Mankind, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4dafdd95
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 324
- path: Criminal Minds, Season 19.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4dafdd95
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 324
- path: Family Guy, Season 24.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4dafdd95
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 324
- path: House of the Dragon, Season 3.jpg
  width: 1080
  height: 1350
  thumb: thumbnails_0.jpg?crc=4dafdd95
  thumb_x: 1728
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 324
- path: Sesame Street, Season 56.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=4dafdd95
  thumb_x: 1987
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 324
