- path: Silo, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: The Boys, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: The Pitt, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: Jujutsu Kaisen, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: One Piece, Season 23.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: For All Mankind, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: Criminal Minds, Season 19.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: Family Guy, Season 24.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: House of the Dragon, Season 3.jpg
  width: 1080
  height: 1350
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 1728
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: Sesame Street, Season 56.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 1987
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: American Idol, Season 24.jpg
  width: 800
  height: 1422
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_y: 324
  thumb_width: 182
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: Big Brother, Season 28.jpg
  width: 800
  height: 1158
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 182
  thumb_y: 324
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: Project Runway, Season 22.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 406
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: Survivor, Season 50.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 649
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: Top Chef, Season 23.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 892
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: Beef, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 1108
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: Fauda, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 1324
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: Lupin, Season 4.jpg
  width: 800
  height: 1005
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 1540
  thumb_y: 324
  thumb_width: 257
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: Frieren Beyond Journey's End, Season 2.jpg
  width: 800
  height: 1131
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 1797
  thumb_y: 324
  thumb_width: 229
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: King of the Hill, Season 15.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_x: 2026
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
- path: The Bear, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1694d7b9
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2242
  thumb_total_height: 972
