- path: The Last of Us Part I.jpeg
  width: 750
  height: 1000
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Tunic.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 243
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Aperture Desk Job.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 459
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: God of War Ragnarok.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 702
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Jurassic World Primal Ops.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 945
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Mount & Blade II Bannerlord.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 1188
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Need for Speed Unbound.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 1431
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Overwatch 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 1674
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Pentiment.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 1917
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Prince of Persia Escape 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 2160
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Prodeus.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Quake Champions.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Return to Monkey Island.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Roach Race.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Signalis.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Stray.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Syberia The World Before.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: The Case of the Golden Idol.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: The Last of Us Part I.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: World of Warcraft Dragonflight.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 2187
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: World of Warcraft Wrath of the Lich King Classic.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Elden Ring.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Kirby and the Forgotten Land.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 486
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Pokémon Scarlet and Violet.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 729
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Citizen Sleeper.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 972
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Vampire Survivors.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=82c3660b
  thumb_x: 1215
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
