- path: The Sopranos, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Curb Your Enthusiasm.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Frasier, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Malcolm in the Middle.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: One Piece, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: One Piece, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: One Piece, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Stargate SG-1, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: The X-Files, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: CSI Crime Scene Investigation.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: ER, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Law & Order, Season 11.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: The West Wing, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: South Park, Season 4.jpg
  width: 667
  height: 1000
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: The Simpsons, Season 12.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Angel, Season 2.jpg
  width: 603
  height: 800
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 244
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Buffy the Vampire Slayer, Season 5.jpg
  width: 621
  height: 800
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 1324
  thumb_y: 324
  thumb_width: 251
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Gilmore Girls.jpg
  width: 1620
  height: 2250
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 1575
  thumb_y: 324
  thumb_width: 233
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Mister Rogers' Neighborhood, Season 30.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 1808
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: NYPD Blue, Season 7.jpg
  width: 1000
  height: 1426
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 2028
  thumb_y: 324
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Oz, Season 4.jpg
  width: 340
  height: 491
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_y: 648
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Saturday Night Live, Season 26.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 224
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Sesame Street, Season 31.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 467
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Sex and the City, Season 3.jpg
  width: 1000
  height: 1426
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 683
  thumb_y: 648
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Ally McBeal, Season 4.jpg
  width: 300
  height: 433
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 910
  thumb_y: 648
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Big Brother.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 1134
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: Survivor.jpg
  width: 800
  height: 1133
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 1350
  thumb_y: 648
  thumb_width: 229
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
- path: The Real World, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=cc1b4b64
  thumb_x: 1579
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2255
  thumb_total_height: 972
