- path: The Sopranos, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8ccee32f
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: Curb Your Enthusiasm.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8ccee32f
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: Frasier, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8ccee32f
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: Malcolm in the Middle.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8ccee32f
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
