- path: The Sopranos, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afc1a74e
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Curb Your Enthusiasm.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afc1a74e
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Frasier, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afc1a74e
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Malcolm in the Middle.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afc1a74e
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: One Piece, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afc1a74e
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: One Piece, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afc1a74e
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: One Piece, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afc1a74e
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Stargate SG-1, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afc1a74e
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: The X-Files, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afc1a74e
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
