- path: Aliens Alien 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8b4d30f3
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 486
  thumb_total_height: 324
- path: Street Fighter.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8b4d30f3
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 486
  thumb_total_height: 324
