- path: Aliens Alien 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9f4ae64
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Street Fighter.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9f4ae64
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Contra.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9f4ae64
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Final Fantasy.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9f4ae64
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Mega Man.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9f4ae64
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: NetHack.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9f4ae64
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Double Dragon.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9f4ae64
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Maniac Mansion.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9f4ae64
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Phantasy Star.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9f4ae64
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: R-Type.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9f4ae64
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Zelda II The Adventure of Link.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9f4ae64
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Tecmo Bowl.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9f4ae64
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Sid Meier's Pirates!.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9f4ae64
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
