- path: Baron Vladimir Harkonnen.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Chani.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Dr. Liet Kynes.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Dr. Wellington Yueh.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Duke Leto Atreides.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Duncan Idaho.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Glossu Rabban.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Gunrey Halleck.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Jamis.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Lady Jessica.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Paul Atreides.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Piter De Vries.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 324
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Reverend Mother Mohiam.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 648
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Shadout Mapes.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 972
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Stilgar.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Thufir Hawat.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ee750f20
  thumb_x: 1620
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
