- path: Doctor Who, Season 15.jpg
  width: 1080
  height: 1620
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: Roots.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 216
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: Saturday Night Live, Season 3.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 436
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: Sesame Street, Season 9.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 679
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: The Carol Burnett Show, Season 11.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 895
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: The Jeffersons, Season 4.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 1115
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: The Muppet Show, Season 2.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 1335
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: Happy Days, Season 5.jpg
  width: 333
  height: 476
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 1555
  thumb_width: 226
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: Barney Miller, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 1781
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: Kojak, Season 5.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 1997
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: Good Times, Season 5.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: Hawaii Five-O, Season 10.jpg
  width: 800
  height: 1000
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 220
  thumb_y: 324
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: Lou Grant.jpg
  width: 800
  height: 1156
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 479
  thumb_y: 324
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: Maude, Season 6.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 703
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: One Day at a Time, Season 3.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 923
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: Soap.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 1143
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
- path: The Bob Newhart Show, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=c1816a91
  thumb_x: 1363
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2217
  thumb_total_height: 648
