- path: Doctor Who, Season 7.jpg
  width: 1080
  height: 1620
  thumb: thumbnails_0.jpg?crc=449867c3
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1094
  thumb_total_height: 324
- path: Mister Rogers' Neighborhood, Season 3.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=449867c3
  thumb_x: 216
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1094
  thumb_total_height: 324
- path: Monty Python's Flying Circus, Season 2.jpg
  width: 343
  height: 500
  thumb: thumbnails_0.jpg?crc=449867c3
  thumb_x: 436
  thumb_width: 222
  thumb_height: 324
  thumb_total_width: 1094
  thumb_total_height: 324
- path: Sesame Street, Season 2.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=449867c3
  thumb_x: 658
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1094
  thumb_total_height: 324
- path: The Carol Burnett Show, Season 4.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=449867c3
  thumb_x: 874
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1094
  thumb_total_height: 324
