- path: Eternal Sunshine of the Spotless Mind.png
  width: 1080
  height: 1600
  thumb: thumbnails_0.png?crc=5a20bb13
  thumb_width: 218
  thumb_height: 324
  thumb_total_width: 218
  thumb_total_height: 324
