- path: Donkey Kong.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=7430663f
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 729
  thumb_total_height: 324
- path: Frogger.jpg
  width: 800
  height: 1069
  thumb: thumbnails_0.jpg?crc=7430663f
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 729
  thumb_total_height: 324
- path: Galaga.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=7430663f
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 729
  thumb_total_height: 324
