- path: Everything Everywhere All at Once.jpeg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: RRR.jpeg
  width: 1000
  height: 1500
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: All Quiet on the Western Front.jpeg
  width: 1000
  height: 1400
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 432
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Bullet Train.jpg
  width: 800
  height: 1201
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 663
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: 'Glass Onion: A Knives Out Mystery.jpg'
  width: 714
  height: 1000
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 879
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: An Irish Goodbye.jpg
  width: 800
  height: 1133
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1110
  thumb_width: 229
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Elvis.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1339
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Guillermo del Toro's Pinocchio.jpg
  width: 800
  height: 1120
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1555
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Navalny.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1786
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: The Banshees of Inisherin.jpg
  width: 800
  height: 1141
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 2002
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: The Whale.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Aftersun.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Avatar The Way of Water.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Babylon.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Black Adam.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Bones and All.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Chip 'n Dale Rescue Rangers.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Close.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Decision to Leave.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1728
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Emily the Criminal.jpg
  width: 800
  height: 1199
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Halloween Ends.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Hotel Transylvania Transformania.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Hundreds of Beavers.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Jurassic World Dominion.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Minions The Rise of Gru.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 864
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Nope.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1080
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Pearl.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1296
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Prey.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1512
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Puss in Boots The Last Wish.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1728
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Scream.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1944
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: The Batman.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: The Fabelmans.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 216
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: The Ice Age Adventures of Buck Wild.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 432
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: The Menu.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 648
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Top Gun Maverick.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 864
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Triangle of Sadness.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1080
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Tár.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1296
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: All Quiet on the Western Front.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1512
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Black Panther Wakanda Forever.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1728
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Criminal City 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1944
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Doctor Strange in the Multiverse of Madness.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Everything Everywhere All at Once.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 216
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Fantastic Beasts The Secrets of Dumbledore.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 432
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Glass Onion A Knives Out Mystery.jpg
  width: 800
  height: 1199
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 648
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Sonic the Hedgehog 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 864
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: The Offer.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1080
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Thor Love and Thunder.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1296
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Diary of a Wimpy Kid Rodrick Rules.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1512
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Dragon Ball Super Super Hero.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1728
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Hellraiser.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=313cba09
  thumb_x: 1944
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 1620
- path: Texas Chainsaw Massacre.jpg
  width: 800
  height: 1200
  thumb: thumbnails_1.jpg?crc=77654a96
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 216
  thumb_total_height: 324
