- path: Everything Everywhere All at Once.jpeg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b8f37d8b
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1110
  thumb_total_height: 324
- path: RRR.jpeg
  width: 1000
  height: 1500
  thumb: thumbnails_0.jpg?crc=b8f37d8b
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1110
  thumb_total_height: 324
- path: All Quiet on the Western Front.jpeg
  width: 1000
  height: 1400
  thumb: thumbnails_0.jpg?crc=b8f37d8b
  thumb_x: 432
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 1110
  thumb_total_height: 324
- path: Bullet Train.jpg
  width: 666
  height: 1000
  thumb: thumbnails_0.jpg?crc=b8f37d8b
  thumb_x: 663
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1110
  thumb_total_height: 324
- path: 'Glass Onion: A Knives Out Mystery.jpg'
  width: 714
  height: 1000
  thumb: thumbnails_0.jpg?crc=b8f37d8b
  thumb_x: 879
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 1110
  thumb_total_height: 324
