- path: Everything Everywhere All at Once.jpeg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=977f55b8
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 663
  thumb_total_height: 324
- path: RRR.jpeg
  width: 1000
  height: 1500
  thumb: thumbnails_0.jpg?crc=977f55b8
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 663
  thumb_total_height: 324
- path: All Quiet on the Western Front.jpeg
  width: 1000
  height: 1400
  thumb: thumbnails_0.jpg?crc=977f55b8
  thumb_x: 432
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 663
  thumb_total_height: 324
