- path: Everything Everywhere All at Once.jpeg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=219ac460
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 432
  thumb_total_height: 324
- path: RRR.jpeg
  width: 1000
  height: 1500
  thumb: thumbnails_0.jpg?crc=219ac460
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 432
  thumb_total_height: 324
