- path: Everything Everywhere All at Once.jpeg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=539370a1
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 216
  thumb_total_height: 324
