- path: The Last of Us American Dreams.jpg
  width: 650
  height: 1000
  thumb: thumbnails_0.jpg?crc=eeafcdff
  thumb_width: 210
  thumb_height: 324
  thumb_total_width: 210
  thumb_total_height: 324
