- path: Aliens Online.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Command & Conquer Red Alert Retaliation.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Disney's Math Quest with Aladdin.jpg
  width: 800
  height: 957
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 486
  thumb_width: 271
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: ESP Ra.De..jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 757
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Fallout 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1000
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Half-Life.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Marvel vs. Capcom Clash of Super Heroes.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Need for Speed III Hot Pursuit.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Resident Evil 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: StarCraft Brood War.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 2215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: StarCraft Insurrection.jpg
  width: 800
  height: 966
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_y: 324
  thumb_width: 268
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: StarCraft Retribution.jpg
  width: 800
  height: 939
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 268
  thumb_y: 324
  thumb_width: 276
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: StarCraft.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 544
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: The Elder Scrolls Adventures Redguard.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 787
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: The Settlers III.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1030
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Tomb Raider III Adventures of Lara Croft.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1273
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Trespasser.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1516
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Worms Pinball.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1759
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Xenogears.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 2002
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: The Legend of Zelda Ocarina of Time.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 2245
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Metal Gear Solid.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Dance Dance Revolution.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Grim Fandango.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 486
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Pokémon Yellow.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 729
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Suikoden II.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 972
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Caesar III.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1215
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Soulcalibur.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1458
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Falcon 4.0.jpg
  width: 800
  height: 952
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1701
  thumb_y: 648
  thumb_width: 272
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: MediEvil.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1973
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: 1080 Snowboarding.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 2216
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: F-Zero X.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Populous The Beginning.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 243
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Daytona USA 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 486
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Ridge Racer Type 4.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 729
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Sega Rally 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 972
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Starsiege Tribes.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1215
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Pokémon Trading Card Game.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1458
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Panzer Dragoon Saga.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1701
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Sonic Adventure.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 1944
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: The House of the Dead 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 2187
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: LSD Dream Emulator.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_y: 1296
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Rugrats Search for Reptar.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 243
  thumb_y: 1296
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Dune 2000.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 486
  thumb_y: 1296
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: The X-Files Game.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 729
  thumb_y: 1296
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
- path: Tex Murphy Overseer.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=ab38942a
  thumb_x: 972
  thumb_y: 1296
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2488
  thumb_total_height: 1620
