- path: Rita Hayworth and Shawshank Redemption.jpg
  width: 640
  height: 985
  thumb: thumbnails_0.jpg?crc=f48acb49
  thumb_width: 210
  thumb_height: 324
  thumb_total_width: 210
  thumb_total_height: 324
