- path: Alien Covenant In Utero.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Assassin's Creed Origins.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Assassin's Creed Unity Arno's Chronicles.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Bridge Constructor Portal.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Danmaku Unlimited 3.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Divinity Original Sin II - Divine Edition.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Forza Motorsport 7.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Friday the 13th The Game.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Hollow Knight.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Need for Speed Payback.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Nex Machina.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: NieR Automata.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Paranormal Activity The Lost Soul.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Resident Evil 7 Biohazard.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Space Pirate Trainer.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: StarCraft Remastered.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Syberia 3.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: The Elder Scrolls Legends.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: VRSE Jurassic World.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=30afe0c2
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
