- path: Alien Covenant In Utero.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Assassin's Creed Origins.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Assassin's Creed Unity Arno's Chronicles.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Bridge Constructor Portal.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Danmaku Unlimited 3.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Divinity Original Sin II - Divine Edition.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Forza Motorsport 7.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Friday the 13th The Game.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Hollow Knight.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Need for Speed Payback.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Nex Machina.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: NieR Automata.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Paranormal Activity The Lost Soul.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Resident Evil 7 Biohazard.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Space Pirate Trainer.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: StarCraft Remastered.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Syberia 3.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: The Elder Scrolls Legends.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: VRSE Jurassic World.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Fortnite Battle Royale.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 2187
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: The Legend of Zelda Breath of the Wild.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: PUBG Battlegrounds.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Cuphead.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 486
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Divinity Original Sin II.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 729
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: What Remains of Edith Finch.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 972
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Tekken 7.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 1215
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Mario Kart 8 Deluxe.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 1458
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Dragon Quest XI Echoes of an Elusive Age.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 1701
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Night in the Woods.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 1944
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Little Nightmares.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 2187
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Destiny 2.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Doki Doki Literature Club!.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 243
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Gorogoa.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 486
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Opus Magnum.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 729
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: SteamWorld Dig 2.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 972
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Fire Emblem Heroes.png
  width: 800
  height: 800
  thumb: thumbnails_0.png?crc=edecf562
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 324
  thumb_total_height: 324
- path: Torment Tides of Numenera.jpg
  width: 800
  height: 1000
  thumb: thumbnails_0.jpg?crc=9885681
  thumb_x: 1215
  thumb_y: 972
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
