- path: Addams Family Values.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Aliens A Comic Book Adventure.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Command & Conquer.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Tekken 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Warcraft II Tides of Darkness.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Worms.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Chrono Trigger.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Super Mario World 2 Yoshis Island.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Donkey Kong Country 2 Diddys Kong Quest.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Full Throttle.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Clock Tower.jpg
  width: 800
  height: 1068
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: MechWarrior 2 31st Century Combat.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Star Wars Dark Forces.jpg
  width: 800
  height: 1020
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 486
  thumb_y: 324
  thumb_width: 254
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Discworld.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 740
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: I Have No Mouth, and I Must Scream.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 983
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: 3D Pinball for Windows - Space Cadet.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 1226
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Ristar.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 1469
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Vectorman.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 1712
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Phantasmagoria.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 1955
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: The Beast Within A Gabriel Knight Mystery.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 2198
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: MTV's Beavis and Butt-Head in Virtual Stupidity.jpg
  width: 800
  height: 1068
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
- path: Sailor Moon Another Story.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f898000b
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2441
  thumb_total_height: 972
