- path: The Continental.jpeg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=ada2a5e7
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 662
  thumb_total_height: 324
- path: Mrs. Davis.jpg
  width: 474
  height: 711
  thumb: thumbnails_0.jpg?crc=ada2a5e7
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 662
  thumb_total_height: 324
- path: The Last of Us.jpg
  width: 426
  height: 600
  thumb: thumbnails_0.jpg?crc=ada2a5e7
  thumb_x: 432
  thumb_width: 230
  thumb_height: 324
  thumb_total_width: 662
  thumb_total_height: 324
