- path: John Wick Chapter 3 – Parabellum.jpg
  width: 533
  height: 798
  thumb: thumbnails_0.jpg?crc=fdc99cc9
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 216
  thumb_total_height: 324
