- path: Mad Men, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: The Wire, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: 30 Rock, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: It's Always Sunny in Philadelphia, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: Breaking Bad.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: Dexter, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: Fringe.jpg
  width: 667
  height: 1000
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: The Penguins of Madagascar.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: One Piece, Season 13.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: Battlestar Galactica, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: Lost, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: CSI Crime Scene Investigation, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: Criminal Minds, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: ER, Season 15.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: Grey's Anatomy, Season 5.jpg
  width: 800
  height: 1141
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 864
  thumb_y: 324
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: House, Season 5.jpg
  width: 800
  height: 1142
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 1091
  thumb_y: 324
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: Law & Order, Season 18.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 1318
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: Law & Order, Season 19.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 1534
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: NCIS, Season 6.jpg
  width: 800
  height: 1134
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 1750
  thumb_y: 324
  thumb_width: 228
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: Family Guy, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 1978
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: South Park, Season 12.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: The Office, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
- path: The Simpsons, Season 20.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e01acdb8
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2194
  thumb_total_height: 972
