- path: All Quiet on the Western Front.jpeg
  width: 958
  height: 1500
  thumb: thumbnails_0.jpg?crc=2a4879a6
  thumb_width: 207
  thumb_height: 324
  thumb_total_width: 207
  thumb_total_height: 324
