- path: Alluri Sitarama Raju.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c42e8c79
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Catherine Buxton.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c42e8c79
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Jennifer.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c42e8c79
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Komram Bheem.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c42e8c79
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Sarojini.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c42e8c79
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Scott Buxton.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c42e8c79
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Sita.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c42e8c79
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Venkata Raman Raji.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c42e8c79
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Venkateswarulu.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c42e8c79
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
