- path: Adjudicator.jpg
  width: 365
  height: 364
  thumb: thumbnails_0.jpg?crc=13fb3cf7
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 323
  thumb_total_width: 3230
  thumb_total_height: 628
- path: Charon O'Connor.jpg
  width: 391
  height: 391
  thumb: thumbnails_0.jpg?crc=13fb3cf7
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3230
  thumb_total_height: 628
- path: Cormac O'Connor.jpg
  width: 376
  height: 376
  thumb: thumbnails_0.jpg?crc=13fb3cf7
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3230
  thumb_total_height: 628
- path: Francis Patrick "Frankie" Scott, Jr..jpg
  width: 287
  height: 288
  thumb: thumbnails_0.jpg?crc=13fb3cf7
  thumb_x: 608
  thumb_y: 324
  thumb_width: 287
  thumb_height: 288
  thumb_total_width: 3230
  thumb_total_height: 628
- path: Gretel.jpg
  width: 304
  height: 304
  thumb: thumbnails_0.jpg?crc=13fb3cf7
  thumb_y: 324
  thumb_width: 304
  thumb_height: 304
  thumb_total_width: 3230
  thumb_total_height: 628
- path: Hansel.jpg
  width: 378
  height: 377
  thumb: thumbnails_0.jpg?crc=13fb3cf7
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 323
  thumb_total_width: 3230
  thumb_total_height: 628
- path: KD ("Kady") Silva.jpg
  width: 467
  height: 467
  thumb: thumbnails_0.jpg?crc=13fb3cf7
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3230
  thumb_total_height: 628
- path: Lou Burton.jpg
  width: 403
  height: 403
  thumb: thumbnails_0.jpg?crc=13fb3cf7
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3230
  thumb_total_height: 628
- path: Mayhew.jpg
  width: 598
  height: 598
  thumb: thumbnails_0.jpg?crc=13fb3cf7
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3230
  thumb_total_height: 628
- path: Miles Burton.jpg
  width: 314
  height: 313
  thumb: thumbnails_0.jpg?crc=13fb3cf7
  thumb_x: 2916
  thumb_width: 314
  thumb_height: 313
  thumb_total_width: 3230
  thumb_total_height: 628
- path: Uncle Charlie.jpg
  width: 683
  height: 683
  thumb: thumbnails_0.jpg?crc=13fb3cf7
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3230
  thumb_total_height: 628
- path: Winston Scott.jpg
  width: 470
  height: 470
  thumb: thumbnails_0.jpg?crc=13fb3cf7
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3230
  thumb_total_height: 628
- path: Yen Scott.jpg
  width: 304
  height: 304
  thumb: thumbnails_0.jpg?crc=13fb3cf7
  thumb_x: 304
  thumb_y: 324
  thumb_width: 304
  thumb_height: 304
  thumb_total_width: 3230
  thumb_total_height: 628
