- path: Raging Bull.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=ae6674b2
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: Star Wars Episode V - The Empire Strikes Back.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=ae6674b2
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: Friday the 13th.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=ae6674b2
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: The Shining.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=ae6674b2
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
