- path: Frasier, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: The New Addams Family.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: Cowboy Bebop.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: Stargate SG-1, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: The X-Files, Season 6.jpg
  width: 600
  height: 900
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: ER, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: Law & Order, Season 9.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: South Park, Season 2.jpg
  width: 800
  height: 1131
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 1512
  thumb_width: 229
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: The Simpsons, Season 10.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 1741
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: Buffy the Vampire Slayer, Season 3.jpg
  width: 619
  height: 800
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 1957
  thumb_width: 251
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: Homicide Life on the Street, Season 7.jpg
  width: 354
  height: 500
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_y: 324
  thumb_width: 229
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: Mister Rogers' Neighborhood, Season 28.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 229
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: NYPD Blue, Season 6.jpg
  width: 1000
  height: 1426
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 449
  thumb_y: 324
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: Oz, Season 2.jpg
  width: 340
  height: 491
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 676
  thumb_y: 324
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: Saturday Night Live, Season 24.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 900
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: Sesame Street, Season 30.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 1143
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: Sex and the City.jpg
  width: 1000
  height: 1426
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 1359
  thumb_y: 324
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
- path: The Larry Sanders Show, Season 6.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=afe34a14
  thumb_x: 1586
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2208
  thumb_total_height: 648
