- path: Super Mario Bros. 3.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=86c4b6c5
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 486
  thumb_total_height: 324
- path: Ninja Gaiden.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=86c4b6c5
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 486
  thumb_total_height: 324
