- path: An Elder Scrolls Legend Battlespire.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Chaos Island The Lost World.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Command & Conquer Red Alert Counterstrike.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Command & Conquer Red Alert The Aftermath.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Command & Conquer Sole Survivor.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Diablo.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Fallout.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Grand Theft Auto.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Need for Speed II.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Quake II.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Street Fighter III 2nd Impact.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Tekken 3.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: The Lost World Jurassic Park - Genesis.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: The Lost World Jurassic Park - Handhelds.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: The Lost World Jurassic Park - PlayStation and Saturn.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: The Lost World Jurassic Park Arcade.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Theme Hospital.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Tomb Raider II.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Worms 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Worms The Director's Cut.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 2187
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Final Fantasy VII.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: GoldenEye 007.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Age of Empires.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 486
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Ultima Online.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 729
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Gran Turismo.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 972
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Riven.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 1215
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: The Curse of Monkey Island.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 1458
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Castlevania Symphony of the Night.jpg
  width: 800
  height: 1056
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 1701
  thumb_y: 648
  thumb_width: 245
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: FIFA Road to World Cup 98.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 1946
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Final Fantasy Tactics.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_x: 2189
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
- path: Klonoa Door to Phantomile.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=edad95ea
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2432
  thumb_total_height: 1296
