- path: Frasier, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Seinfeld, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Friends.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: The X-Files, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: ER.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Law & Order, Season 5.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: The Simpsons, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: The Fresh Prince of Bel-Air, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Homicide Life on the Street, Season 2.jpg
  width: 354
  height: 500
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 1728
  thumb_width: 229
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Homicide Life on the Street, Season 3.jpg
  width: 351
  height: 500
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 1957
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Mister Rogers' Neighborhood, Season 24.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: NYPD Blue, Season 2.jpg
  width: 1000
  height: 1426
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 220
  thumb_y: 324
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Roseanne, Season 7.jpg
  width: 1383
  height: 2048
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 447
  thumb_y: 324
  thumb_width: 219
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Saturday Night Live, Season 20.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 666
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Sesame Street, Season 26.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 909
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: The Larry Sanders Show, Season 3.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 1125
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: My So-Called Life.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 1345
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Northern Exposure, Season 6.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 1561
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: The Real World, Season 3.jpg
  width: 800
  height: 1155
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 1781
  thumb_y: 324
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Animaniacs, Season 2.jpg
  width: 800
  height: 1156
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 2005
  thumb_y: 324
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Batman The Animated Series, Season 3.jpg
  width: 800
  height: 1156
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_y: 648
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Beavis and Butt-Head, Season 4.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 224
  thumb_y: 648
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Beavis and Butt-Head, Season 5.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 444
  thumb_y: 648
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Dragon Ball Z, Season 8.jpg
  width: 800
  height: 1119
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 664
  thumb_y: 648
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Murphy Brown, Season 7.jpg
  width: 800
  height: 1104
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 895
  thumb_y: 648
  thumb_width: 234
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Beverly Hills, 90210, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 1129
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Boy Meets World, Season 2.jpg
  width: 800
  height: 1144
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 1345
  thumb_y: 648
  thumb_width: 226
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
- path: Melrose Place, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1fbccf4d
  thumb_x: 1571
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2229
  thumb_total_height: 972
