- path: Fester's Quest.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f6ba5d86
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Final Fight.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f6ba5d86
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Friday the 13th.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f6ba5d86
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Prince of Persia.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f6ba5d86
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: SimCity.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=f6ba5d86
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Populous.jpg
  width: 800
  height: 1068
  thumb: thumbnails_0.jpg?crc=f6ba5d86
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Wonder Boy III The Dragons Trap.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=f6ba5d86
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Teenage Mutant Ninja Turtles.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f6ba5d86
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Chip's Challenge.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f6ba5d86
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Bonk's Adventure.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=f6ba5d86
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Herzog Zwei.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f6ba5d86
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Disney's DuckTales.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f6ba5d86
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Who Framed Roger Rabbit.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=f6ba5d86
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
