- path: Apron Man.jpg
  width: 347
  height: 346
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_y: 324
  thumb_width: 324
  thumb_height: 323
  thumb_total_width: 3240
  thumb_total_height: 647
- path: Arthur Schrodinger.jpg
  width: 506
  height: 507
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 647
- path: Celeste Abbott.jpg
  width: 512
  height: 512
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 647
- path: Clara.jpg
  width: 421
  height: 420
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 323
  thumb_total_width: 3240
  thumb_total_height: 647
- path: Hans Ziegler.jpg
  width: 463
  height: 463
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 647
- path: JQ.jpg
  width: 514
  height: 514
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 647
- path: Jay.jpg
  width: 299
  height: 298
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_x: 629
  thumb_y: 324
  thumb_width: 299
  thumb_height: 298
  thumb_total_width: 3240
  thumb_total_height: 647
- path: Joy.jpg
  width: 282
  height: 282
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_x: 928
  thumb_y: 324
  thumb_width: 282
  thumb_height: 282
  thumb_total_width: 3240
  thumb_total_height: 647
- path: Mathilde LaFleur.jpg
  width: 591
  height: 590
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 323
  thumb_total_width: 3240
  thumb_total_height: 647
- path: Montgomery Abbott.jpg
  width: 381
  height: 381
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 647
- path: Mother Superior.jpg
  width: 278
  height: 278
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_x: 1210
  thumb_y: 324
  thumb_width: 278
  thumb_height: 278
  thumb_total_width: 3240
  thumb_total_height: 647
- path: Preston Wiley.jpg
  width: 420
  height: 421
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 647
- path: Sister Simone.jpg
  width: 457
  height: 457
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 647
- path: The Boss.jpg
  width: 305
  height: 304
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_x: 324
  thumb_y: 324
  thumb_width: 305
  thumb_height: 304
  thumb_total_width: 3240
  thumb_total_height: 647
- path: The Pope.jpg
  width: 394
  height: 395
  thumb: thumbnails_0.jpg?crc=81760185
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 647
