- path: Amandine Poulain.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Amelie Poulain.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Collignon.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Dominique Bretodeau.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Eva.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Georgette.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Gina.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Hipolito.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Joseph.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Lucien.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Madeleine Wallace.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Mr. Collignon.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 324
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Nino Quincampoix.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 648
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Philomène.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 972
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Raphaël Poulain.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Raymond Dufayel.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 1620
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Suzanne.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Young Amelie.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 2268
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: young Dominique.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=e5460b18
  thumb_x: 2592
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
