- path: Assassin's Creed Chronicles China.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Assassin's Creed Syndicate.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Crypt of the NecroDancer.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Forza Motorsport 6.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Hotline Miami 2 Wrong Number.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Jurassic Park Arcade.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Jurassic World The Game.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Lara Croft Go.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Lara Croft Relic Run.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Lego Jurassic World.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Metal Gear Solid V The Phantom Pain.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Need for Speed No Limits.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Need for Speed.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Rise of the Tomb Raider.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: SpongeBob HeroPants.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: StarCraft II Legacy of the Void.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: The Witcher 3 Wild Hunt.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: The Witcher Battle Arena.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Worms 4.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Worms World Party Remastered.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 2187
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Bloodborne.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Undertale.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Rocket League.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 486
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Cities Skylines.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 729
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Kerbal Space Program.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 972
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Life Is Strange.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 1215
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Splatoon.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=98092767
  thumb_x: 1458
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
