- path: Chris Pine.jpg
  width: 903
  height: 903
  thumb: thumbnails_0.jpg?crc=4a72a618
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2494
  thumb_total_height: 324
- path: Hugh Grant.jpg
  width: 1067
  height: 1067
  thumb: thumbnails_0.jpg?crc=4a72a618
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2494
  thumb_total_height: 324
- path: Justice Smith.jpg
  width: 782
  height: 782
  thumb: thumbnails_0.jpg?crc=4a72a618
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2494
  thumb_total_height: 324
- path: Michelle Rodriguez.jpg
  width: 1196
  height: 1196
  thumb: thumbnails_0.jpg?crc=4a72a618
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2494
  thumb_total_height: 324
- path: Sophia Lillis.jpg
  width: 982
  height: 982
  thumb: thumbnails_0.jpg?crc=4a72a618
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2494
  thumb_total_height: 324
- path: Steve Jobs.jpeg
  width: 733
  height: 733
  thumb: thumbnails_0.jpg?crc=4a72a618
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2494
  thumb_total_height: 324
- path: Regé-Jean Page.jpg
  width: 832
  height: 832
  thumb: thumbnails_0.jpg?crc=4a72a618
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2494
  thumb_total_height: 324
- path: Keanu Reeves.jpg
  width: 226
  height: 226
  thumb: thumbnails_0.jpg?crc=4a72a618
  thumb_x: 2268
  thumb_width: 226
  thumb_height: 226
  thumb_total_width: 2494
  thumb_total_height: 324
