- path: Cheers, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=c8a79d8
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2198
  thumb_total_height: 648
- path: Seinfeld.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=c8a79d8
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2198
  thumb_total_height: 648
- path: Chip 'n Dale Rescue Rangers.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=c8a79d8
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2198
  thumb_total_height: 648
- path: The Simpsons.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=c8a79d8
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2198
  thumb_total_height: 648
- path: Doctor Who, Season 26.jpg
  width: 1080
  height: 1620
  thumb: thumbnails_0.jpg?crc=c8a79d8
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2198
  thumb_total_height: 648
- path: Mister Rogers' Neighborhood, Season 20.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=c8a79d8
  thumb_x: 1080
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2198
  thumb_total_height: 648
- path: Roseanne, Season 2.jpg
  width: 1383
  height: 2048
  thumb: thumbnails_0.jpg?crc=c8a79d8
  thumb_x: 1300
  thumb_width: 219
  thumb_height: 324
  thumb_total_width: 2198
  thumb_total_height: 648
- path: Saturday Night Live, Season 15.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=c8a79d8
  thumb_x: 1519
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2198
  thumb_total_height: 648
- path: Sesame Street, Season 21.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=c8a79d8
  thumb_x: 1762
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2198
  thumb_total_height: 648
- path: The Cosby Show, Season 6.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=c8a79d8
  thumb_x: 1978
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2198
  thumb_total_height: 648
- path: The Golden Girls, Season 5.jpg
  width: 1000
  height: 1500
  thumb: thumbnails_0.jpg?crc=c8a79d8
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2198
  thumb_total_height: 648
