- path: Cheers, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Seinfeld.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Chip 'n Dale Rescue Rangers.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: The Simpsons.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Doctor Who, Season 26.jpg
  width: 1080
  height: 1620
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Mister Rogers' Neighborhood, Season 20.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 1080
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Roseanne, Season 2.jpg
  width: 1383
  height: 2048
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 1300
  thumb_width: 219
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Saturday Night Live, Season 15.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 1519
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Sesame Street, Season 21.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 1762
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: The Cosby Show, Season 6.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 1978
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: The Golden Girls, Season 5.jpg
  width: 1000
  height: 1500
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Dallas, Season 13.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 216
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Quantum Leap, Season 2.jpg
  width: 1500
  height: 2005
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 436
  thumb_y: 324
  thumb_width: 242
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Quantum Leap.jpg
  width: 1611
  height: 2208
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 678
  thumb_y: 324
  thumb_width: 236
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: The Wonder Years, Season 3.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 914
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: thirtysomething, Season 3.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 1134
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Blackadder, Season 4.jpg
  width: 800
  height: 1151
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 1354
  thumb_y: 324
  thumb_width: 225
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Dragon Ball Z.jpg
  width: 800
  height: 1120
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 1579
  thumb_y: 324
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: A Different World, Season 3.jpg
  width: 800
  height: 1121
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 1810
  thumb_y: 324
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: L.A. Law, Season 4.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 2041
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Murphy Brown, Season 2.jpg
  width: 800
  height: 1104
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_y: 648
  thumb_width: 234
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: China Beach, Season 3.jpg
  width: 800
  height: 1133
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 234
  thumb_y: 648
  thumb_width: 229
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
- path: Newhart, Season 8.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=89c9e051
  thumb_x: 463
  thumb_y: 648
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2261
  thumb_total_height: 972
