- path: Cheers, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f7f92b2c
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1598
  thumb_total_height: 324
- path: Doctor Who, Season 22.jpg
  width: 287
  height: 347
  thumb: thumbnails_0.jpg?crc=f7f92b2c
  thumb_x: 216
  thumb_width: 267
  thumb_height: 324
  thumb_total_width: 1598
  thumb_total_height: 324
- path: Mister Rogers' Neighborhood, Season 16.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=f7f92b2c
  thumb_x: 483
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1598
  thumb_total_height: 324
- path: Saturday Night Live, Season 11.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=f7f92b2c
  thumb_x: 703
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 1598
  thumb_total_height: 324
- path: Sesame Street, Season 17.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=f7f92b2c
  thumb_x: 946
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1598
  thumb_total_height: 324
- path: The Cosby Show, Season 2.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=f7f92b2c
  thumb_x: 1162
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1598
  thumb_total_height: 324
- path: The Golden Girls.jpg
  width: 1000
  height: 1500
  thumb: thumbnails_0.jpg?crc=f7f92b2c
  thumb_x: 1382
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1598
  thumb_total_height: 324
