- path: ARC Raiders.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Abiotic Factor.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Amerzone The Explorer's Legacy.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Ascent DX.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Assassin's Creed Shadows.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Ball x Pit.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Blue Prince.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Dispatch.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Donkey Kong Bananza.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Hades II.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Hollow Knight Silksong.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Hollywood Animal.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: JETRUNNER.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Jump Space.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Jurassic World Evolution 3.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Megabonk.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Skate Story.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: SpongeBob SquarePants Titans of the Tide.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Sword of the Sea.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Syberia Remastered.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 2187
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Syberia VR.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: The Alters.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: The Outer Worlds 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 486
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: The Rogue Prince of Persia.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 729
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Tomb Raider IV-VI Remastered.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 972
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: World of Warcraft Mists of Pandaria Classic.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 1215
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Worms Across Worlds.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=adce082a
  thumb_x: 1458
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
