- path: Cheers, Season 10.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Seinfeld, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Seinfeld, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Law & Order, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: The Simpsons, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: The Fresh Prince of Bel-Air, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Mister Rogers' Neighborhood, Season 22.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 1296
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Roseanne, Season 4.jpg
  width: 1383
  height: 2048
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 1516
  thumb_width: 219
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Saturday Night Live, Season 17.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 1735
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Sesame Street, Season 23.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 1978
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: The Cosby Show, Season 8.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: The Golden Girls, Season 7.jpg
  width: 1000
  height: 1500
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 220
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Northern Exposure, Season 2.jpg
  width: 520
  height: 741
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 436
  thumb_y: 324
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Northern Exposure, Season 3.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 663
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Quantum Leap, Season 4.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 883
  thumb_y: 324
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: The Wonder Years, Season 5.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 1107
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Dragon Ball Z, Season 3.jpg
  width: 800
  height: 1120
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 1327
  thumb_y: 324
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Dragon Ball Z, Season 4.jpg
  width: 800
  height: 1119
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 1558
  thumb_y: 324
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Prime Suspect.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 1789
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
- path: Rugrats.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=60feefd9
  thumb_x: 2009
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2225
  thumb_total_height: 648
