- path: Alien 3 - Game Boy.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Alien 3 - SNES.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Alien 3 The Gun.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Alien vs Predator - SNES.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Alien vs Predator The Last of His Clan.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Jurassic Park - Amiga and DOS.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Jurassic Park - Game Gear and Master System.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Jurassic Park - Genesis.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Jurassic Park - NES and Game Boy.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Jurassic Park - SNES.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Jurassic Park - Sega CD.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Myst.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Prince of Persia 2 The Shadow and the Flame.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: The Addams Family Pugsley's Scavenger Hunt.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: The Settlers.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Daytona USA.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: SimCity 2000.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: The Legend of Zelda Links Awakening.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Day of the Tentacle.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Gabriel Knight Sins of the Fathers.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 2187
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Sam & Max Hit the Road.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Gunstar Heroes.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Mega Man X.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 486
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: FIFA International Soccer.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 729
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Madden NFL 94.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 972
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: NBA Jam.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1215
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: NHL 94.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1458
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Ogre Battle The March of the Black Queen.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1701
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Star Fox.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1944
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Return to Zork.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 2187
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: The 7th Guest.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Master of Orion.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 243
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: SimFarm.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 486
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Ridge Racer.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 729
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Phantasy Star IV The End of the Millennium.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 972
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Shining Force II.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1215
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Bubsy in Claws Encounters of the Furred Kind.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1458
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Cool Spot.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1701
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Rocket Knight Adventures.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 1944
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Disney's Goof Troop.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8496a9b7
  thumb_x: 2187
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
