- path: Alien 3 - Game Boy.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Alien 3 - SNES.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Alien 3 The Gun.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Alien vs Predator - SNES.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Alien vs Predator The Last of His Clan.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Jurassic Park - Amiga and DOS.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Jurassic Park - Game Gear and Master System.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Jurassic Park - Genesis.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Jurassic Park - NES and Game Boy.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Jurassic Park - SNES.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Jurassic Park - Sega CD.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Myst.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Prince of Persia 2 The Shadow and the Flame.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: The Addams Family Pugsley's Scavenger Hunt.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: The Settlers.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Daytona USA.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: SimCity 2000.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=80a60d3
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
