- path: Harry Potter and the Philosopher's Stone.jpg
  width: 1600
  height: 2400
  thumb: thumbnails_0.jpg?crc=4c58273a
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 216
  thumb_total_height: 324
