- path: Gunsmoke, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=c24c4baa
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 660
  thumb_total_height: 324
- path: Perry Mason, Season 2.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=c24c4baa
  thumb_x: 216
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 660
  thumb_total_height: 324
- path: Alfred Hitchcock Presents, Season 4.jpg
  width: 800
  height: 1156
  thumb: thumbnails_0.jpg?crc=c24c4baa
  thumb_x: 436
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 660
  thumb_total_height: 324
