- path: Cheers, Season 11.jpg
  width: 800
  height: 1133
  thumb: thumbnails_0.jpg?crc=65a09a5b
  thumb_width: 229
  thumb_height: 324
  thumb_total_width: 661
  thumb_total_height: 324
- path: Seinfeld, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=65a09a5b
  thumb_x: 229
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 661
  thumb_total_height: 324
- path: Law & Order, Season 3.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=65a09a5b
  thumb_x: 445
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 661
  thumb_total_height: 324
