- path: Cheers, Season 11.jpg
  width: 800
  height: 1133
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_width: 229
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Seinfeld, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 229
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Law & Order, Season 3.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 445
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: The Simpsons, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 661
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: The Fresh Prince of Bel-Air, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 877
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Mister Rogers' Neighborhood, Season 23.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 1093
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Roseanne, Season 5.jpg
  width: 1383
  height: 2048
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 1313
  thumb_width: 219
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Saturday Night Live, Season 18.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 1532
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Sesame Street, Season 24.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 1775
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: The Larry Sanders Show.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 1991
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Northern Exposure, Season 4.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Quantum Leap, Season 5.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 220
  thumb_y: 324
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: The Wonder Years, Season 6.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 444
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: The Real World.jpg
  width: 800
  height: 1155
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 664
  thumb_y: 324
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Batman The Animated Series.jpg
  width: 800
  height: 1156
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 888
  thumb_y: 324
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Beavis and Butt-Head.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 1112
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Dragon Ball Z, Season 5.jpg
  width: 800
  height: 1120
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 1332
  thumb_y: 324
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Dragon Ball Z, Season 6.jpg
  width: 800
  height: 1120
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 1563
  thumb_y: 324
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Prime Suspect, Season 2.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 1794
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Rugrats, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 2014
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: A Different World, Season 6.jpg
  width: 800
  height: 889
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_y: 648
  thumb_width: 291
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: L.A. Law, Season 7.jpg
  width: 800
  height: 872
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 291
  thumb_y: 648
  thumb_width: 297
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Murphy Brown, Season 5.jpg
  width: 800
  height: 1104
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 588
  thumb_y: 648
  thumb_width: 234
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Beverly Hills, 90210, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 822
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Melrose Place.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 1038
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Murder, She Wrote, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 1254
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
- path: Sailor Moon.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e24e7276
  thumb_x: 1470
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2230
  thumb_total_height: 972
