- path: Star Wars Episode 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1fcdb061
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: Suspiria.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1fcdb061
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: Halloween with the New Addams Family.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=1fcdb061
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: The Spy Who Loved Me.jpg
  width: 800
  height: 1199
  thumb: thumbnails_0.jpg?crc=1fcdb061
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
