- path: Debbie.jpg
  width: 390
  height: 390
  thumb: thumbnails_0.jpg?crc=38425f20
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Deirdre Beaubeirdre.jpg
  width: 386
  height: 386
  thumb: thumbnails_0.jpg?crc=38425f20
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Evelyn Wang.jpg
  width: 607
  height: 607
  thumb: thumbnails_0.jpg?crc=38425f20
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Gong Gong.jpg
  width: 388
  height: 387
  thumb: thumbnails_0.jpg?crc=38425f20
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 323
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Joy Wang.jpg
  width: 1278
  height: 1278
  thumb: thumbnails_0.jpg?crc=38425f20
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Waymond Wang.jpg
  width: 957
  height: 957
  thumb: thumbnails_0.jpg?crc=38425f20
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
