- path: The Matrix.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d549f902
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 432
  thumb_total_height: 324
- path: The Thirteenth Floor.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d549f902
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 432
  thumb_total_height: 324
