- path: Cooper.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=63b7d915
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Dr. Josephine Grant.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=63b7d915
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Jamie.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=63b7d915
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Lady Raven.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=63b7d915
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Logan.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=63b7d915
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Marnie McPhail.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=63b7d915
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Rachel.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=63b7d915
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Riley.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=63b7d915
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
- path: Spotter.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=63b7d915
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2916
  thumb_total_height: 324
