- path: The Last of Us Left Behind.jpg
  width: 600
  height: 776
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_width: 250
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Alien Isolation.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 250
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Aliens Armageddon.jpg
  width: 668
  height: 1080
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 493
  thumb_width: 200
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Assassin's Creed Freedom Cry.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 693
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Assassin's Creed Memories.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 936
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Assassin's Creed Rogue.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 1179
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Assassin's Creed Unity.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 1422
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Counter-Strike Nexon Studio.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 1665
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Divinity Original Sin.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 1908
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Fable Anniversary.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 2151
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Forza Horizon 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Hearthstone.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Lara Croft and the Temple of Osiris.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Metal Gear Solid V Ground Zeroes.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Penguins of Madagascar.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Sunset Overdrive.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: The Binding of Isaac Rebirth.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: The Elder Scrolls Online.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: The Talos Principle.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: The Witcher Adventure Game.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 2187
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Titanfall.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Watch Dogs.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: World of Warcraft Warlords of Draenor.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 486
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Worms Battlegrounds.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 729
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Destiny.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 972
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Mario Kart 8.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 1215
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Dragon Age Inquisition.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 1458
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Donkey Kong Country Tropical Freeze.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 1701
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: The Sims 4.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 1944
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Five Nights at Freddys.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 2187
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: The Evil Within.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Monument Valley.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 243
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: TowerFall Ascension.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 486
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Crossy Road.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 729
  thumb_y: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Middle-earth Shadow of Mordor.jpg
  width: 800
  height: 1070
  thumb: thumbnails_0.jpg?crc=5dcbcaf3
  thumb_x: 1053
  thumb_y: 972
  thumb_width: 242
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
