- path: Alexis.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=7ba6140a
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Amelia "Mia" Dolan.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=7ba6140a
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Bill.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=7ba6140a
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Caitlin.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=7ba6140a
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Keith.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=7ba6140a
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Laura Wilder.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=7ba6140a
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Sebastian "Seb" Wilder.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=7ba6140a
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Tracy.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=7ba6140a
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
