- path: Community, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Curb Your Enthusiasm, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: It's Always Sunny in Philadelphia, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Modern Family, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Parks and Recreation, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Parks and Recreation, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Black Mirror.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Breaking Bad, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Dexter, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Game of Thrones.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Haven, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Luther, Season 2.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 216
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: The Walking Dead, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 436
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: One Piece, Season 14.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 652
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: One Piece, Season 15.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 868
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: CSI Crime Scene Investigation, Season 12.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1084
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Criminal Minds, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1300
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Grey's Anatomy, Season 8.jpg
  width: 800
  height: 1141
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1516
  thumb_y: 324
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Homeland.jpg
  width: 667
  height: 1000
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1743
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: House, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1959
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: NCIS, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Adventure Time, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Archer, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Archer, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Bob's Burgers.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 864
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Family Guy, Season 10.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1080
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Ice Age A Mammoth Christmas.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1296
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Phineas and Ferb, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1512
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Regular Show, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1728
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: South Park, Season 15.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1944
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: The Office, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: The Simpsons, Season 23.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 216
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Doctor Who, Season 6.jpg
  width: 1045
  height: 1417
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 432
  thumb_y: 972
  thumb_width: 239
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Downton Abbey, Season 2.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 671
  thumb_y: 972
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Saturday Night Live, Season 37.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 891
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: Sesame Street, Season 42.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1134
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
- path: The Good Wife, Season 3.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=3b0abdf2
  thumb_x: 1350
  thumb_y: 972
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 1296
