- path: Mad Men, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=c38ffdb6
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1728
  thumb_total_height: 324
- path: The Americans.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=c38ffdb6
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1728
  thumb_total_height: 324
- path: Arrested Development, Season 4.jpg
  width: 533
  height: 800
  thumb: thumbnails_0.jpg?crc=c38ffdb6
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1728
  thumb_total_height: 324
- path: Brooklyn Nine-Nine.jpg
  width: 533
  height: 800
  thumb: thumbnails_0.jpg?crc=c38ffdb6
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1728
  thumb_total_height: 324
- path: Community, Season 4.jpg
  width: 533
  height: 800
  thumb: thumbnails_0.jpg?crc=c38ffdb6
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1728
  thumb_total_height: 324
- path: It's Always Sunny in Philadelphia, Season 9.jpg
  width: 533
  height: 800
  thumb: thumbnails_0.jpg?crc=c38ffdb6
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1728
  thumb_total_height: 324
- path: Modern Family, Season 5.jpg
  width: 533
  height: 800
  thumb: thumbnails_0.jpg?crc=c38ffdb6
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1728
  thumb_total_height: 324
- path: Parks and Recreation, Season 6.jpg
  width: 533
  height: 800
  thumb: thumbnails_0.jpg?crc=c38ffdb6
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1728
  thumb_total_height: 324
