- path: Alena 'Alex' Xenakis.jpeg
  width: 270
  height: 270
  thumb: thumbnails_0.jpg?crc=4ac061d2
  thumb_x: 2528
  thumb_width: 270
  thumb_height: 270
  thumb_total_width: 3060
  thumb_total_height: 572
- path: Aurore Cassel.jpg
  width: 414
  height: 414
  thumb: thumbnails_0.jpg?crc=4ac061d2
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3060
  thumb_total_height: 572
- path: Aymeric Cassel.jpg
  width: 477
  height: 477
  thumb: thumbnails_0.jpg?crc=4ac061d2
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3060
  thumb_total_height: 572
- path: Johnny Silverhand.jpeg
  width: 715
  height: 715
  thumb: thumbnails_0.jpg?crc=4ac061d2
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3060
  thumb_total_height: 572
- path: Kurt Hansen.jpeg
  width: 262
  height: 262
  thumb: thumbnails_0.jpg?crc=4ac061d2
  thumb_x: 2798
  thumb_width: 262
  thumb_height: 262
  thumb_total_width: 3060
  thumb_total_height: 572
- path: Mr. Hands.jpg
  width: 531
  height: 531
  thumb: thumbnails_0.jpg?crc=4ac061d2
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3060
  thumb_total_height: 572
- path: Rosalind Myers.jpeg
  width: 273
  height: 273
  thumb: thumbnails_0.jpg?crc=4ac061d2
  thumb_x: 2255
  thumb_width: 273
  thumb_height: 273
  thumb_total_width: 3060
  thumb_total_height: 572
- path: Solomon Reed.jpeg
  width: 311
  height: 311
  thumb: thumbnails_0.jpg?crc=4ac061d2
  thumb_x: 1944
  thumb_width: 311
  thumb_height: 311
  thumb_total_width: 3060
  thumb_total_height: 572
- path: Song So Mi 'Songbird'.jpeg
  width: 248
  height: 248
  thumb: thumbnails_0.jpg?crc=4ac061d2
  thumb_y: 324
  thumb_width: 248
  thumb_height: 248
  thumb_total_width: 3060
  thumb_total_height: 572
- path: V (female).jpeg
  width: 567
  height: 567
  thumb: thumbnails_0.jpg?crc=4ac061d2
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3060
  thumb_total_height: 572
- path: V (male).jpeg
  width: 541
  height: 541
  thumb: thumbnails_0.jpg?crc=4ac061d2
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3060
  thumb_total_height: 572
