- path: Albert Einstein.jpg
  width: 357
  height: 358
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 629
- path: Boris Pash.jpg
  width: 372
  height: 372
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 629
- path: David Hill.jpg
  width: 361
  height: 360
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 323
  thumb_total_width: 3240
  thumb_total_height: 629
- path: Edward Teller.jpg
  width: 278
  height: 278
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_x: 305
  thumb_y: 324
  thumb_width: 278
  thumb_height: 278
  thumb_total_width: 3240
  thumb_total_height: 629
- path: Ernest Lawrence.jpg
  width: 1200
  height: 1199
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 323
  thumb_total_width: 3240
  thumb_total_height: 629
- path: Frank Oppenheimer.jpg
  width: 535
  height: 535
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 629
- path: Jean Tatlock.jpg
  width: 305
  height: 305
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_y: 324
  thumb_width: 305
  thumb_height: 305
  thumb_total_width: 3240
  thumb_total_height: 629
- path: Kitty Oppenheimer.jpg
  width: 333
  height: 333
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 629
- path: Leslie Groves.jpg
  width: 421
  height: 421
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 629
- path: Lewis Strauss.jpg
  width: 494
  height: 495
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 629
- path: Neils Bohr.jpg
  width: 266
  height: 267
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_x: 857
  thumb_y: 324
  thumb_width: 266
  thumb_height: 267
  thumb_total_width: 3240
  thumb_total_height: 629
- path: Richard Feynman.jpg
  width: 274
  height: 274
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_x: 583
  thumb_y: 324
  thumb_width: 274
  thumb_height: 274
  thumb_total_width: 3240
  thumb_total_height: 629
- path: Roger Robb.jpg
  width: 814
  height: 814
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 629
- path: J. Robert Oppenheimer.jpeg
  width: 723
  height: 723
  thumb: thumbnails_0.jpg?crc=6b08f214
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 629
