- path: Airline Stewardess.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Blackmailed Man.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Carol.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Chester.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Cooper's mother.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Cooper.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Electro Station Attendant.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Hansen.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Hector.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Josh Peters.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Karen.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Katie.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 324
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Kenny.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 648
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Lacie Pound.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 972
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Man in Jail.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Ryan Pound.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 1620
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Shou.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Sonja.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 2268
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Susan.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=c2d361ab
  thumb_x: 2592
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
