- path: Better Call Saul.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: The Americans, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: True Detective, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Brooklyn Nine-Nine, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Community, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: It's Always Sunny in Philadelphia, Season 10.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Modern Family, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Parks and Recreation, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Agent Carter.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Fargo, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Game of Thrones, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Killjoys.jpg
  width: 566
  height: 800
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 216
  thumb_y: 324
  thumb_width: 229
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Luther, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 445
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Narcos.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 661
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Rectify, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 877
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Sense8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 1093
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: One Punch Man.jpeg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 1309
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: The Expanse.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 1525
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Criminal Minds, Season 11.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 1741
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Grey's Anatomy, Season 12.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 1957
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: Homeland, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
- path: NCIS, Season 13.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=efda258e
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2173
  thumb_total_height: 972
