- path: Better Call Saul.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: The Americans, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: True Detective, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Brooklyn Nine-Nine, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Community, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: It's Always Sunny in Philadelphia, Season 10.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Modern Family, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Parks and Recreation, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Agent Carter.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Fargo, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Game of Thrones, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Killjoys.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Luther, Season 4.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 432
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Narcos.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 652
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Rectify, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 868
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Sense8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1084
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: One Punch Man.jpeg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1300
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: The Expanse.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1516
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Criminal Minds, Season 11.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1732
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Grey's Anatomy, Season 12.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1948
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Homeland, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: NCIS, Season 13.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Adventure Time, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Archer, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: BoJack Horseman, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 864
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Bob's Burgers, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1080
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Family Guy, Season 14.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1296
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Regular Show, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1512
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: South Park, Season 19.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1728
  thumb_y: 648
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Steven Universe, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1952
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: The Simpsons, Season 27.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Halt and Catch Fire, Season 2.jpg
  width: 569
  height: 800
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 216
  thumb_y: 972
  thumb_width: 230
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Mr. Robot.jpg
  width: 561
  height: 800
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 446
  thumb_y: 972
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Orphan Black, Season 3.jpg
  width: 553
  height: 800
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 673
  thumb_y: 972
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: The Leftovers, Season 2.jpg
  width: 561
  height: 800
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 897
  thumb_y: 972
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Doctor Who, Season 9.jpg
  width: 800
  height: 1117
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1124
  thumb_y: 972
  thumb_width: 232
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Downton Abbey, Season 6.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1356
  thumb_y: 972
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Orange Is the New Black, Season 3.jpg
  width: 300
  height: 433
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1576
  thumb_y: 972
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Saturday Night Live, Season 41.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1800
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: The Good Wife, Season 7.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 2043
  thumb_y: 972
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Veep, Season 4.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_y: 1296
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Chef's Table.jpg
  width: 300
  height: 433
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 224
  thumb_y: 1296
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: The Jinx.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 448
  thumb_y: 1296
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Hannibal, Season 3.jpg
  width: 1000
  height: 1426
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 668
  thumb_y: 1296
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Justified, Season 6.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 895
  thumb_y: 1296
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: American Idol, Season 14.jpg
  width: 800
  height: 1156
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1119
  thumb_y: 1296
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Big Brother, Season 17.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1343
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Keeping Up with the Kardashians, Season 10.jpg
  width: 800
  height: 1156
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1559
  thumb_y: 1296
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Keeping Up with the Kardashians, Season 11.jpg
  width: 800
  height: 1128
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 1783
  thumb_y: 1296
  thumb_width: 230
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: Project Runway, Season 14.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=409330f6
  thumb_x: 2013
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2263
  thumb_total_height: 1620
- path: RuPaul's Drag Race, Season 7.jpg
  width: 800
  height: 1176
  thumb: thumbnails_1.jpg?crc=b27b3e03
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1620
  thumb_total_height: 324
- path: Survivor, Season 30.jpg
  width: 800
  height: 1120
  thumb: thumbnails_1.jpg?crc=b27b3e03
  thumb_x: 220
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 1620
  thumb_total_height: 324
- path: Survivor, Season 31.jpg
  width: 800
  height: 1120
  thumb: thumbnails_1.jpg?crc=b27b3e03
  thumb_x: 451
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 1620
  thumb_total_height: 324
- path: The Amazing Race, Season 26.jpg
  width: 800
  height: 1156
  thumb: thumbnails_1.jpg?crc=b27b3e03
  thumb_x: 682
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 1620
  thumb_total_height: 324
- path: The Amazing Race, Season 27.jpg
  width: 800
  height: 1156
  thumb: thumbnails_1.jpg?crc=b27b3e03
  thumb_x: 906
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 1620
  thumb_total_height: 324
- path: The Bachelor, Season 19.jpg
  width: 800
  height: 1065
  thumb: thumbnails_1.jpg?crc=b27b3e03
  thumb_x: 1130
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 1620
  thumb_total_height: 324
- path: Top Chef, Season 13.jpg
  width: 800
  height: 1050
  thumb: thumbnails_1.jpg?crc=b27b3e03
  thumb_x: 1373
  thumb_width: 247
  thumb_height: 324
  thumb_total_width: 1620
  thumb_total_height: 324
