- path: Assassin's Creed Black Flag Resynced.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=6ad774b4
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Forza Horizon 6.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=6ad774b4
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: God of War Sons of Sparta.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=6ad774b4
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: MIO Memories in Orbit.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=6ad774b4
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Marathon.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=6ad774b4
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Mewgenics.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=6ad774b4
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Mixtape.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=6ad774b4
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Pragmata.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=6ad774b4
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Rayman Legends Retold.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=6ad774b4
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Resident Evil Requiem.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=6ad774b4
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Saros.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=6ad774b4
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: World of Warcraft Midnight.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=6ad774b4
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
