- path: Ayesha.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6e418edf
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Baby Groot.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6e418edf
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Drax the Destroyer.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6e418edf
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Ego.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6e418edf
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Gamora.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6e418edf
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Mainframe.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6e418edf
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Mantis.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6e418edf
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Nebula.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6e418edf
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Peter Quill _ Star-Lord.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6e418edf
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Rocket Raccoon.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6e418edf
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Stakar Ogord.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6e418edf
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Taserface.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6e418edf
  thumb_x: 324
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Yondu Udonta.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=6e418edf
  thumb_x: 648
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
