- path: Doctor Who, Season 4.jpg
  width: 1080
  height: 1620
  thumb: thumbnails_0.jpg?crc=bd1628e9
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1096
  thumb_total_height: 324
- path: The Andy Griffith Show, Season 7.jpg
  width: 340
  height: 491
  thumb: thumbnails_0.jpg?crc=bd1628e9
  thumb_x: 216
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 1096
  thumb_total_height: 324
- path: Bewitched, Season 3.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=bd1628e9
  thumb_x: 440
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1096
  thumb_total_height: 324
- path: Mission Impossible.jpg
  width: 1400
  height: 2100
  thumb: thumbnails_0.jpg?crc=bd1628e9
  thumb_x: 660
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1096
  thumb_total_height: 324
- path: The Fugitive, Season 4.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=bd1628e9
  thumb_x: 876
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1096
  thumb_total_height: 324
