- path: The Andy Griffith Show, Season 3.jpg
  width: 340
  height: 491
  thumb: thumbnails_0.jpg?crc=5436df7a
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 444
  thumb_total_height: 324
- path: The Dick Van Dyke Show, Season 2.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=5436df7a
  thumb_x: 224
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 444
  thumb_total_height: 324
