- path: Better Call Saul, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Brooklyn Nine-Nine, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Curb Your Enthusiasm, Season 10.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Ted Lasso.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Central Park.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Devs.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Industry.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Infinity Train, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Infinity Train, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Madagascar A Little Wild.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Ozark, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Star Trek Picard.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: The Boys, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: The Mandalorian, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: What We Do in the Shadows, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Attack on Titan, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Jujutsu Kaisen.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Dark, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: The Expanse, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1728
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Criminal Minds, Season 15.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Grey's Anatomy, Season 17.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Homeland, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: NCIS, Season 18.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Archer, Season 11.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Bluey, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 864
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Bob's Burgers, Season 11.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1080
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Family Guy, Season 19.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1296
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: South Park, Season 24.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1512
  thumb_y: 648
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: The Simpsons, Season 32.jpg
  width: 666
  height: 1000
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1732
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
- path: Westworld, Season 3.jpg
  width: 561
  height: 800
  thumb: thumbnails_0.jpg?crc=4020bf3c
  thumb_x: 1948
  thumb_y: 648
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2175
  thumb_total_height: 972
