- path: Better Call Saul, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Brooklyn Nine-Nine, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Curb Your Enthusiasm, Season 10.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Ted Lasso.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Central Park.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Devs.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Industry.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Infinity Train, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Infinity Train, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Madagascar A Little Wild.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Ozark, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Star Trek Picard.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: The Boys, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: The Mandalorian, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: What We Do in the Shadows, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Attack on Titan, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Jujutsu Kaisen.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Dark, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: The Expanse, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1728
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Criminal Minds, Season 15.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Grey's Anatomy, Season 17.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Homeland, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: NCIS, Season 18.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Archer, Season 11.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Bluey, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 864
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Bob's Burgers, Season 11.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1080
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Family Guy, Season 19.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1296
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: South Park, Season 24.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1512
  thumb_y: 648
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: The Simpsons, Season 32.jpg
  width: 666
  height: 1000
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1732
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Westworld, Season 3.jpg
  width: 561
  height: 800
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1948
  thumb_y: 648
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Doctor Who, Season 12.jpg
  width: 1055
  height: 1500
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_y: 972
  thumb_width: 228
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: I May Destroy You.jpg
  width: 1013
  height: 1500
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 228
  thumb_y: 972
  thumb_width: 219
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Insecure, Season 4.jpg
  width: 1000
  height: 1426
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 447
  thumb_y: 972
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Killing Eve, Season 3.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 674
  thumb_y: 972
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Saturday Night Live, Season 46.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 894
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Sesame Street, Season 51.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1137
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: The Crown, Season 4.jpg
  width: 1147
  height: 1606
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1353
  thumb_y: 972
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: The Queen's Gambit.jpg
  width: 1730
  height: 2600
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1584
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: This Is Us, Season 5.jpg
  width: 750
  height: 1000
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1800
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Cosmos, Season 3.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 2043
  thumb_y: 972
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: The Last Dance.jpg
  width: 941
  height: 1317
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_y: 1296
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: American Idol, Season 18.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 231
  thumb_y: 1296
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Big Brother, Season 22.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 451
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Keeping Up with the Kardashians, Season 18.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 667
  thumb_y: 1296
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Keeping Up with the Kardashians, Season 19.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 910
  thumb_y: 1296
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: RuPaul's Drag Race, Season 12.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1153
  thumb_y: 1296
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: RuPaul's Drag Race, Season 13.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1373
  thumb_y: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Survivor, Season 40.jpg
  width: 800
  height: 1137
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1697
  thumb_y: 1296
  thumb_width: 228
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: The Amazing Race, Season 32.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 1925
  thumb_y: 1296
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: The Bachelor, Season 24.jpg
  width: 800
  height: 1167
  thumb: thumbnails_0.jpg?crc=d290c61a
  thumb_x: 2145
  thumb_y: 1296
  thumb_width: 222
  thumb_height: 324
  thumb_total_width: 2367
  thumb_total_height: 1620
- path: Top Chef, Season 17.jpg
  width: 800
  height: 1200
  thumb: thumbnails_1.jpg?crc=83de4f50
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 216
  thumb_total_height: 324
