- path: Aliens.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=44849658
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 1458
  thumb_total_height: 324
- path: Super Mario World.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=44849658
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 1458
  thumb_total_height: 324
- path: The Secret of Monkey Island.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=44849658
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 1458
  thumb_total_height: 324
- path: Dr. Mario.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=44849658
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 1458
  thumb_total_height: 324
- path: Smash TV.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=44849658
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 1458
  thumb_total_height: 324
- path: ActRaiser.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=44849658
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 1458
  thumb_total_height: 324
