- path: They Shouldn't Have Killed His Dog.jpg
  width: 985
  height: 1500
  thumb: thumbnails_0.jpg?crc=932b2b4e
  thumb_width: 212
  thumb_height: 324
  thumb_total_width: 212
  thumb_total_height: 324
