- path: Captain Commando.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Sonic the Hedgehog.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Street Fighter II The World Warrior.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Streets of Rage.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Sid Meier's Civilization.jpg
  width: 800
  height: 1068
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: The Legend of Zelda A Link to the Past.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Lemmings.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Metroid II Return of Samus.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Final Fantasy IV.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Monkey Island 2 LeChucks Revenge.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Super Ghouls n Ghosts.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: The Simpsons Arcade Game.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Another World.jpg
  width: 800
  height: 1068
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: ToeJam & Earl.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: FreeCell.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: SkiFree.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: SimAnt.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Battletoads.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Joe & Mac.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
- path: Teenage Mutant Ninja Turtles Turtles in Time.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=b0d930a1
  thumb_x: 2187
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 648
