- path: Bill.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=eda633cc
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: David.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=eda633cc
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Ellie.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=eda633cc
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Henry.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=eda633cc
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Joel.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=eda633cc
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Maria.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=eda633cc
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Marlene.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=eda633cc
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Riley.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=eda633cc
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Sam.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=eda633cc
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Sarah.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=eda633cc
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Tess.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=eda633cc
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Tommy.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=eda633cc
  thumb_x: 324
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
