- path: Aliens vs. Pinball.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Assassin's Creed Chronicles India.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Assassin's Creed Chronicles Russia.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Assassin's Creed Identity.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Beholder.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Darkest Dungeon.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Doom.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Forza Horizon 3.jpg
  width: 800
  height: 1068
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Hyper Light Drifter.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: INSIDE.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Mirror's Edge Catalyst.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: No Man's Sky.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Overwatch.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Oxenfree.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Persona 5.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: StarCraft II Nova Covert Ops.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: This Is the Police.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Titanfall 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Trackmania Turbo.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Watch Dogs 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 2187
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: World of Warcraft Legion.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Worms W.M.D.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Stardew Valley.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 486
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Sid Meier's Civilization VI.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 729
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Pokémon Go.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 972
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Stellaris.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 1215
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Dead by Daylight.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 1458
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Clash Royale.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=90eb93a1
  thumb_x: 1701
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
