- path: Aliens vs. Pinball.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Assassin's Creed Chronicles India.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Assassin's Creed Chronicles Russia.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Assassin's Creed Identity.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Beholder.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Darkest Dungeon.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Doom.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Forza Horizon 3.jpg
  width: 800
  height: 1068
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Hyper Light Drifter.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: INSIDE.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Mirror's Edge Catalyst.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: No Man's Sky.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Overwatch.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Oxenfree.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Persona 5.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: StarCraft II Nova Covert Ops.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: This Is the Police.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Titanfall 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Trackmania Turbo.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Watch Dogs 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 2187
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: World of Warcraft Legion.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Worms W.M.D.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Stardew Valley.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 486
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Sid Meier's Civilization VI.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 729
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Pokémon Go.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 972
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Stellaris.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1215
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Dead by Daylight.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1458
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Clash Royale.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1701
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: The Witness.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1944
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Shadow Tactics Blades of the Shogun.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 2187
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Thumper.jpg
  width: 800
  height: 999
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_y: 972
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: American Truck Simulator.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 259
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Planet Coaster.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 475
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Battlefield 1.jpg
  width: 800
  height: 1197
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 691
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Tyranny.jpg
  width: 800
  height: 1107
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 907
  thumb_y: 972
  thumb_width: 234
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Dont Starve Together.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1141
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Starbound.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1384
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Shadowverse.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1627
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Zero Escape Zero Time Dilemma.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 1870
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Arizona Sunshine.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 2113
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: I Expect You to Die.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_y: 1296
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Job Simulator The 2050 Archives.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 243
  thumb_y: 1296
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
- path: Superhot VR.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5bb1c40
  thumb_x: 486
  thumb_y: 1296
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1620
