- path: Alessa.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=90080b8e
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
- path: Cheryl.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=90080b8e
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
- path: Cybil Bennett.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=90080b8e
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
- path: Dahlia Gillespie.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=90080b8e
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
- path: Dr. Michael Kaufmann.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=90080b8e
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
- path: Harry Mason.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=90080b8e
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
- path: Lisa Garland.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=90080b8e
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
