- path: Clementine Kruczynski.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=cceb3f32
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Dr. Howard Mierzwiak.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=cceb3f32
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Joel Barish.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=cceb3f32
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Mary Svevo.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=cceb3f32
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Patrick Wertz.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=cceb3f32
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Stan Fink.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=cceb3f32
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
