- path: Better Call Saul, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: The Americans, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Brooklyn Nine-Nine, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: It's Always Sunny in Philadelphia, Season 11.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Modern Family, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Agent Carter, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Atlanta.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Billions.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Black Mirror, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Easy.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 1944
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Fleabag.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Game of Thrones, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Killjoys, Season 2.jpg
  width: 566
  height: 800
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 432
  thumb_y: 324
  thumb_width: 229
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Narcos, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 661
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Rectify, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 877
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Stranger Things.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9d8f50b2
  thumb_x: 1093
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
