- path: Dungeons & Dragons.png
  width: 1500
  height: 1500
  thumb: thumbnails_0.png?crc=249f9c5e
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 324
  thumb_total_height: 324
- path: Cyberpunk.jpg
  width: 1147
  height: 1491
  thumb: thumbnails_0.jpg?crc=d9de1ff6
  thumb_width: 249
  thumb_height: 324
  thumb_total_width: 249
  thumb_total_height: 324
