- path: Dungeons & Dragons.png
  width: 1500
  height: 1500
  thumb: thumbnails_0.png?crc=249f9c5e
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 324
  thumb_total_height: 324
- path: Cyberpunk.jpg
  width: 1147
  height: 1491
  thumb: thumbnails_0.jpg?crc=3e3a56d6
  thumb_width: 249
  thumb_height: 324
  thumb_total_width: 573
  thumb_total_height: 324
- path: The Last of Us Escape the Dark.jpg
  width: 1000
  height: 1000
  thumb: thumbnails_0.jpg?crc=3e3a56d6
  thumb_x: 249
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 573
  thumb_total_height: 324
