- path: Dungeons & Dragons.png
  width: 1500
  height: 1500
  thumb: thumbnails_0.png?crc=7714c4c9
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2604
  thumb_total_height: 324
- path: Cyberpunk.jpg
  width: 1147
  height: 1491
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1351
  thumb_width: 249
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: The Last of Us Escape the Dark.jpg
  width: 1000
  height: 1000
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 911
  thumb_y: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Catan.jpg
  width: 800
  height: 985
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 555
  thumb_width: 263
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Codenames.jpg
  width: 800
  height: 600
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_y: 1296
  thumb_width: 324
  thumb_height: 243
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Dominion.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1027
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Gloomhaven.jpg
  width: 800
  height: 571
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 648
  thumb_y: 1296
  thumb_width: 324
  thumb_height: 231
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Magic The Gathering.jpg
  width: 800
  height: 1117
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1600
  thumb_width: 232
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Monopoly.jpg
  width: 800
  height: 425
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1944
  thumb_y: 1296
  thumb_width: 324
  thumb_height: 172
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Pandemic.jpg
  width: 800
  height: 1103
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 2156
  thumb_width: 235
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Risk.jpg
  width: 800
  height: 488
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1620
  thumb_y: 1296
  thumb_width: 324
  thumb_height: 197
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Scrabble.jpg
  width: 800
  height: 530
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1296
  thumb_y: 1296
  thumb_width: 324
  thumb_height: 214
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Terraforming Mars.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 254
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Ticket to Ride.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 578
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Warhammer 40,000.jpg
  width: 800
  height: 554
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 972
  thumb_y: 1296
  thumb_width: 324
  thumb_height: 224
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Wingspan.jpg
  width: 800
  height: 782
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1635
  thumb_y: 972
  thumb_width: 324
  thumb_height: 316
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Azul.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1352
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Blades in the Dark.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1676
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Chess.jpg
  width: 800
  height: 736
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 2283
  thumb_y: 972
  thumb_width: 324
  thumb_height: 298
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Diplomacy.jpg
  width: 800
  height: 1126
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 2157
  thumb_y: 324
  thumb_width: 230
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Go.jpg
  width: 800
  height: 774
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1959
  thumb_y: 972
  thumb_width: 324
  thumb_height: 313
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Pathfinder Roleplaying Game.jpg
  width: 800
  height: 987
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_y: 648
  thumb_width: 263
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Twilight Imperium.jpg
  width: 800
  height: 644
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 2607
  thumb_y: 972
  thumb_width: 324
  thumb_height: 260
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Backgammon.png
  width: 800
  height: 521
  thumb: thumbnails_0.png?crc=7714c4c9
  thumb_x: 1956
  thumb_width: 324
  thumb_height: 211
  thumb_total_width: 2604
  thumb_total_height: 324
- path: Call of Cthulhu.png
  width: 800
  height: 1034
  thumb: thumbnails_0.png?crc=7714c4c9
  thumb_x: 324
  thumb_width: 251
  thumb_height: 324
  thumb_total_width: 2604
  thumb_total_height: 324
- path: Cards Against Humanity.png
  width: 800
  height: 420
  thumb: thumbnails_0.png?crc=7714c4c9
  thumb_x: 2280
  thumb_width: 324
  thumb_height: 170
  thumb_total_width: 2604
  thumb_total_height: 324
- path: Munchkin.png
  width: 800
  height: 1212
  thumb: thumbnails_0.png?crc=7714c4c9
  thumb_x: 575
  thumb_width: 214
  thumb_height: 324
  thumb_total_width: 2604
  thumb_total_height: 324
- path: Vampire The Masquerade.png
  width: 800
  height: 1169
  thumb: thumbnails_0.png?crc=7714c4c9
  thumb_x: 789
  thumb_width: 221
  thumb_height: 324
  thumb_total_width: 2604
  thumb_total_height: 324
- path: Agricola.jpg
  width: 800
  height: 1120
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Apocalypse World.jpg
  width: 800
  height: 1227
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 902
  thumb_y: 324
  thumb_width: 211
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Arkham Horror.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 2011
  thumb_y: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Brass Birmingham.png
  width: 800
  height: 800
  thumb: thumbnails_0.png?crc=7714c4c9
  thumb_x: 1010
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2604
  thumb_total_height: 324
- path: Dungeon World.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1471
  thumb_y: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: FATE Core.png
  width: 800
  height: 1511
  thumb: thumbnails_0.png?crc=7714c4c9
  thumb_x: 1334
  thumb_width: 171
  thumb_height: 324
  thumb_total_width: 2604
  thumb_total_height: 324
- path: Fiasco.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1795
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Mork Borg.png
  width: 800
  height: 1070
  thumb: thumbnails_0.png?crc=7714c4c9
  thumb_x: 1505
  thumb_width: 242
  thumb_height: 324
  thumb_total_width: 2604
  thumb_total_height: 324
- path: Power Grid.jpg
  width: 800
  height: 1098
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1235
  thumb_y: 648
  thumb_width: 236
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Puerto Rico.jpg
  width: 800
  height: 1125
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 2335
  thumb_y: 648
  thumb_width: 230
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Scythe.jpg
  width: 800
  height: 592
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 324
  thumb_y: 1296
  thumb_width: 324
  thumb_height: 239
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Shadowrun.jpg
  width: 800
  height: 1024
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_y: 972
  thumb_width: 253
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Spirit Island.jpg
  width: 800
  height: 900
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 253
  thumb_y: 972
  thumb_width: 288
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Twilight Struggle.jpg
  width: 800
  height: 1103
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 541
  thumb_y: 972
  thumb_width: 235
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Android Netrunner.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 776
  thumb_y: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Blood on the Clocktower.jpg
  width: 800
  height: 1226
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1100
  thumb_y: 972
  thumb_width: 211
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Burning Wheel.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1311
  thumb_y: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Cyberpunk 2020.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 2565
  thumb_y: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Cyberpunk Red.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 263
  thumb_y: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: GURPS.jpg
  width: 800
  height: 1034
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 2387
  thumb_y: 324
  thumb_width: 251
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Ironsworn.jpg
  width: 800
  height: 976
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1892
  thumb_y: 324
  thumb_width: 265
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Legend of the Five Rings.jpg
  width: 800
  height: 1085
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1113
  thumb_y: 324
  thumb_width: 239
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Numenera.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 231
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Paranoia.jpg
  width: 800
  height: 1021
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_y: 324
  thumb_width: 254
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Rifts.jpg
  width: 800
  height: 1037
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 2391
  thumb_width: 250
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Tales from the Loop.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 1832
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Ten Candles.png
  width: 800
  height: 1237
  thumb: thumbnails_0.png?crc=7714c4c9
  thumb_x: 1747
  thumb_width: 209
  thumb_height: 324
  thumb_total_width: 2604
  thumb_total_height: 324
- path: The One Ring Roleplaying Game.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 587
  thumb_y: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
- path: Traveller.jpg
  width: 800
  height: 1236
  thumb: thumbnails_0.jpg?crc=eae507af
  thumb_x: 818
  thumb_width: 209
  thumb_height: 324
  thumb_total_width: 2931
  thumb_total_height: 1539
