- path: Animal Well.jpg
  width: 666
  height: 1000
  thumb: thumbnails_0.jpg?crc=9dad34bb
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 972
  thumb_total_height: 324
- path: Silent Hill 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9dad34bb
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 972
  thumb_total_height: 324
- path: Call of Duty Black Ops 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=9dad34bb
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 972
  thumb_total_height: 324
- path: Balatro.jpg
  width: 1200
  height: 675
  thumb: thumbnails_0.jpg?crc=9dad34bb
  thumb_x: 648
  thumb_width: 324
  thumb_height: 182
  thumb_total_width: 972
  thumb_total_height: 324
