- path: Animal Well.jpg
  width: 666
  height: 1000
  thumb: thumbnails_0.jpg?crc=31a7823f
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 648
  thumb_total_height: 324
- path: Silent Hill 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=31a7823f
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 648
  thumb_total_height: 324
- path: Call of Duty Black Ops 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=31a7823f
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 648
  thumb_total_height: 324
