- path: Animal Well.jpg
  width: 666
  height: 1000
  thumb: thumbnails_0.jpg?crc=22c0f090
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 432
  thumb_total_height: 324
- path: Silent Hill 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=22c0f090
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 432
  thumb_total_height: 324
