- path: Doctor Who, Season 12.jpg
  width: 291
  height: 342
  thumb: thumbnails_0.jpg?crc=5dd264e7
  thumb_width: 275
  thumb_height: 324
  thumb_total_width: 1156
  thumb_total_height: 324
- path: Mister Rogers' Neighborhood, Season 7.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=5dd264e7
  thumb_x: 275
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1156
  thumb_total_height: 324
- path: Monty Python's Flying Circus, Season 4.jpg
  width: 348
  height: 500
  thumb: thumbnails_0.jpg?crc=5dd264e7
  thumb_x: 495
  thumb_width: 225
  thumb_height: 324
  thumb_total_width: 1156
  thumb_total_height: 324
- path: Sesame Street, Season 6.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=5dd264e7
  thumb_x: 720
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1156
  thumb_total_height: 324
- path: The Carol Burnett Show, Season 8.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=5dd264e7
  thumb_x: 936
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1156
  thumb_total_height: 324
