- path: Amour.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Argo.jpg
  width: 800
  height: 1141
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 216
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Avengers.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 443
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Beasts of the Southern Wild.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 659
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Cloud Atlas.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 875
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Django Unchained.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1091
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Dredd.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1307
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Evangelion 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1523
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Frances Ha.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1739
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Holy Motors.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1955
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Hotel Transylvania.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Ice Age Continental Drift.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: It's Such a Beautiful Day.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Life of Pi.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Lincoln.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Madagascar 3 Europe's Most Wanted.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Magic Mike.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Men in Black 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Moonrise Kingdom.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1728
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Paranormal Activity 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Pitch Perfect.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Prometheus.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Resident Evil Damnation.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Resident Evil Retribution.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Silver Linings Playbook.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 864
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Skyfall.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1080
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Spring Breakers.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1296
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: The Act of Killing.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1512
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: The Bourne Legacy.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1728
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: The Cabin in the Woods.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 1944
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: The Dark Knight Rises.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: The Hobbit An Unexpected Journey.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 216
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: The Hunger Games.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 432
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: The Master.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 648
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
- path: Zero Dark Thirty.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=58bc30fc
  thumb_x: 864
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2171
  thumb_total_height: 1296
