- path: Aliens Fireteam Elite.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: Forza Horizon 5.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: Jurassic World Evolution 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: Marvel's Guardians of the Galaxy.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: Pathfinder Wrath of the Righteous.jpg
  width: 800
  height: 1072
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_x: 972
  thumb_width: 241
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: Resident Evil Village.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_x: 1213
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: Returnal.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_x: 1456
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: Road 96.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_x: 1699
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: The Addams Family Mansion Mayhem.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_x: 1942
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: The Witcher Monster Slayer.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_x: 2185
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: World of Warcraft Burning Crusade Classic.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: Metroid Dread.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: Halo Infinite.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: Inscryption.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
- path: The Forgotten City.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=5cca369c
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 648
