- path: Aliens Fireteam Elite.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Forza Horizon 5.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Jurassic World Evolution 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Marvel's Guardians of the Galaxy.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Pathfinder Wrath of the Righteous.jpg
  width: 800
  height: 1072
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 972
  thumb_width: 241
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Resident Evil Village.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 1213
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Returnal.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 1456
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Road 96.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 1699
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: The Addams Family Mansion Mayhem.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 1942
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: The Witcher Monster Slayer.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 2185
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: World of Warcraft Burning Crusade Classic.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Metroid Dread.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Halo Infinite.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Inscryption.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: The Forgotten City.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Guilty Gear Strive.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Monster Hunter Rise.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Farming Simulator 22.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Subnautica Below Zero.jpg
  width: 800
  height: 1068
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 1917
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Resident Evil 4 VR.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 2160
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Far Cry 6.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: The Dark Pictures Anthology House of Ashes.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Twelve Minutes.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 486
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Demon Slayer Kimetsu no Yaiba - The Hinokami Chronicles.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 729
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Sherlock Holmes Chapter One.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 972
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: Hot Wheels Unleashed.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 1215
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
- path: The Artful Escape.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=8ea058
  thumb_x: 1458
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2428
  thumb_total_height: 972
