- path: Ant-Man and the Wasp.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Black Panther.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Mission Impossible Fallout.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: An Elephant Sitting Still.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Annihilation.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Aquaman.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Beautiful Boy.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: BlacKkKlansman.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Bohemian Rhapsody.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Bumblebee.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Burning.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Climax.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Cold War.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Crazy Rich Asians.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Creed II.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Deadpool 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Eighth Grade.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: First Reformed.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Green Book.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1728
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Halloween.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Happy as Lazzaro.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Hereditary.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Hotel Transylvania 3 Summer Vacation.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: If Beale Street Could Talk.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Insidious The Last Key.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 864
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Isle of Dogs.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1080
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Jurassic World Fallen Kingdom.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1296
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Long Day's Journey Into Night.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1512
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Mandy.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1728
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Mowgli Legend of the Jungle.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1944
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Roma.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Shoplifters.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 216
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Solo A Star Wars Story.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 432
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Sorry to Bother You.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 648
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: The Cloverfield Paradox.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 864
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: The Favourite.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1080
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: The First Purge.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1296
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: The Night Comes for Us.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1512
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: The Nun.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1728
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: The Predator.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1944
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Tomb Raider.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Upgrade.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 216
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Venom.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 432
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Fantastic Beasts The Crimes of Grindelwald.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 648
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Incredibles 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 864
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Infinity War.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1080
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Maze Runner The Death Cure.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1296
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Ocean's 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1512
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Spider-Man Into the Spider-Verse.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1728
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: The Equalizer 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=107d455
  thumb_x: 1944
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 1620
- path: Dragon Ball Super Broly.jpg
  width: 800
  height: 1200
  thumb: thumbnails_1.jpg?crc=49016e0c
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1080
  thumb_total_height: 324
- path: Hellraiser Judgment.jpg
  width: 800
  height: 1200
  thumb: thumbnails_1.jpg?crc=49016e0c
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1080
  thumb_total_height: 324
- path: Master Z The Ip Man Legacy.jpg
  width: 800
  height: 1200
  thumb: thumbnails_1.jpg?crc=49016e0c
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1080
  thumb_total_height: 324
- path: My Hero Academia Two Heroes.jpg
  width: 800
  height: 1200
  thumb: thumbnails_1.jpg?crc=49016e0c
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1080
  thumb_total_height: 324
- path: Pokémon the Movie The Power of Us.jpg
  width: 800
  height: 1200
  thumb: thumbnails_1.jpg?crc=49016e0c
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1080
  thumb_total_height: 324
