- path: Better Call Saul, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Atlanta, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Atlanta, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Central Park, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Euphoria, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Moon Knight.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Ozark, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Peacemaker.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Resident Evil.jpg
  width: 800
  height: 1199
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Severance.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Star Trek Picard, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Star Trek Strange New Worlds.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Stranger Things, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: The Bear.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: The Boys, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Undone, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Wednesday.jpg
  width: 800
  height: 1185
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 219
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: What We Do in the Shadows, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1515
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Andor.jpg
  width: 667
  height: 1000
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1731
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Cyberpunk Edgerunners.jpeg
  width: 1500
  height: 2222
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1947
  thumb_y: 324
  thumb_width: 219
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: For All Mankind, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: 'Star Trek: Strange New Worlds.jpg'
  width: 1000
  height: 1500
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Criminal Minds, Season 16.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Grey's Anatomy, Season 19.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Law & Order, Season 21.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 864
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Law & Order, Season 22.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1080
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: NCIS, Season 20.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1296
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Archer, Season 13.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1512
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Bob's Burgers, Season 13.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1728
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Family Guy, Season 21.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 1944
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: Ice Age Scrat Tales.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: South Park, Season 25.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 216
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
- path: The Simpsons, Season 34.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bcbc8a5
  thumb_x: 432
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2166
  thumb_total_height: 1296
