- path: Claudia Wolf.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47628e0
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1296
  thumb_total_height: 324
- path: Douglas Cartland.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47628e0
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1296
  thumb_total_height: 324
- path: Heather.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47628e0
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1296
  thumb_total_height: 324
- path: Vincent Smith.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47628e0
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1296
  thumb_total_height: 324
