- path: Better Call Saul, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Succession.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: The Americans, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Arrested Development, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: It's Always Sunny in Philadelphia, Season 13.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Modern Family, Season 10.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Atlanta, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Legion, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Maniac.jpg
  width: 735
  height: 1102
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Ozark, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: The Purge.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Attack on Titan, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: The Expanse, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: The X-Files, Season 11.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Criminal Minds, Season 14.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Grey's Anatomy, Season 15.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Homeland, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: NCIS, Season 16.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Archer, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 1728
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Bluey.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: BoJack Horseman, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Bob's Burgers, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Family Guy, Season 17.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Goliath, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: South Park, Season 22.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 864
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: The Simpsons, Season 30.jpg
  width: 667
  height: 1000
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 1080
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Westworld, Season 2.jpg
  width: 553
  height: 800
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 1296
  thumb_y: 648
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: One Strange Rock.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=8080874e
  thumb_x: 1520
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2160
  thumb_total_height: 972
- path: Kidding.png
  width: 360
  height: 203
  thumb: thumbnails_0.png?crc=f05e64e1
  thumb_width: 324
  thumb_height: 182
  thumb_total_width: 324
  thumb_total_height: 182
