- path: It's Always Sunny in Philadelphia, Season 17.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Adolescence.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Alien Earth.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Andor, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Common Side Effects.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: It Welcome to Derry.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Paradise.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Peacemaker, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Pluribus.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Severance, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Star Trek Strange New Worlds, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Stranger Things, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Task.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: The Last of Us, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: The Pitt.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: The Studio.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Foundation, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Criminal Minds, Season 18.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Grey's Anatomy, Season 22.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1728
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Law & Order, Season 25.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: NCIS, Season 23.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Bob's Burgers, Season 16.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Family Guy, Season 23.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Phineas and Ferb, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: South Park, Season 27.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 864
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: South Park, Season 28.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1080
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: The Simpsons, Season 37.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1296
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Bel-Air, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1512
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Abbott Elementary, Season 5.jpg
  width: 1080
  height: 1350
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1728
  thumb_y: 648
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Doctor Who, Season 2.jpg
  width: 1920
  height: 2880
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1987
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Saturday Night Live, Season 51.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Sesame Street, Season 55.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 243
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Squid Game, Season 3.jpg
  width: 1080
  height: 1350
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 459
  thumb_y: 972
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: The Handmaid's Tale, Season 6.jpg
  width: 1080
  height: 1350
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 718
  thumb_y: 972
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: The White Lotus, Season 3.jpg
  width: 3000
  height: 4444
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 977
  thumb_y: 972
  thumb_width: 219
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
- path: Yellowjackets, Season 3.jpg
  width: 1000
  height: 1481
  thumb: thumbnails_0.jpg?crc=40359de6
  thumb_x: 1196
  thumb_y: 972
  thumb_width: 219
  thumb_height: 324
  thumb_total_width: 2203
  thumb_total_height: 1296
