- path: Akira.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=9558673f
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2850
  thumb_total_height: 570
- path: Bowery King.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=9558673f
  thumb_x: 285
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2850
  thumb_total_height: 570
- path: Caine.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=9558673f
  thumb_x: 570
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2850
  thumb_total_height: 570
- path: Charon.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=9558673f
  thumb_x: 855
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2850
  thumb_total_height: 570
- path: Chidi.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=9558673f
  thumb_x: 1140
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2850
  thumb_total_height: 570
- path: John Wick.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=9558673f
  thumb_x: 1425
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2850
  thumb_total_height: 570
- path: Katia.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=9558673f
  thumb_x: 1710
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2850
  thumb_total_height: 570
- path: Killa.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=9558673f
  thumb_x: 1995
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2850
  thumb_total_height: 570
- path: Shimazu.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=9558673f
  thumb_x: 2280
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2850
  thumb_total_height: 570
- path: The Harbinger.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=9558673f
  thumb_x: 2565
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2850
  thumb_total_height: 570
- path: The Marquis.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=9558673f
  thumb_y: 285
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2850
  thumb_total_height: 570
- path: The Tracker.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=9558673f
  thumb_x: 285
  thumb_y: 285
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2850
  thumb_total_height: 570
- path: Winston.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=9558673f
  thumb_x: 570
  thumb_y: 285
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2850
  thumb_total_height: 570
