- path: Dune Part Two.jpg
  width: 1000
  height: 1500
  thumb: thumbnails_0.jpg?crc=150f605b
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 432
  thumb_total_height: 324
- path: Trap.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=150f605b
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 432
  thumb_total_height: 324
