- path: Aphrodite.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Apollo.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Asterion.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Athena.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Calliope.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Eros.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Freddie.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Grace.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Hecate.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Hermes.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Medusa.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Orpheus.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 324
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Pan.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 648
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Persephone.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 972
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Venus.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: the Oracle.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9af0b731
  thumb_x: 1620
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
