- path: The Matrix Reloaded.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a10acb68
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 432
  thumb_total_height: 324
- path: The Matrix Revolutions.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a10acb68
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 432
  thumb_total_height: 324
