- path: Alien vs Predator - Jaguar.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Alien vs. Predator - Arcade.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Beneath a Steel Sky.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Disney's Activity Center Aladdin.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Jurassic Park 2 The Chaos Continues.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Jurassic Park Arcade.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Jurassic Park Interactive.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 1458
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Jurassic Park Rampage Edition.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 1701
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Marathon.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 1944
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Sonic & Knuckles.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 2187
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Sonic the Hedgehog 3.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Streets of Rage 3.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Tekken.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: The Elder Scrolls Arena.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: The Need for Speed.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Warcraft Orcs & Humans.jpg
  width: 800
  height: 1065
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: X-COM UFO Defense.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Doom II.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Super Metroid.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Donkey Kong Country.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 2187
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: EarthBound.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Virtua Fighter 2.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
- path: Final Fantasy VI.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=befaa15
  thumb_x: 486
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 972
