- path: Doric.jpg
  width: 645
  height: 645
  thumb: thumbnails_0.jpg?crc=3122c22f
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Edgin.jpg
  width: 730
  height: 730
  thumb: thumbnails_0.jpg?crc=3122c22f
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Forge.jpg
  width: 800
  height: 800
  thumb: thumbnails_0.jpg?crc=3122c22f
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Holga.jpg
  width: 673
  height: 673
  thumb: thumbnails_0.jpg?crc=3122c22f
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Simon.jpg
  width: 691
  height: 691
  thumb: thumbnails_0.jpg?crc=3122c22f
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Xenk.jpg
  width: 725
  height: 725
  thumb: thumbnails_0.jpg?crc=3122c22f
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
