- path: One Flew Over the Cuckoo's Nest.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bbc7e262
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 648
  thumb_total_height: 324
- path: Jaws.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bbc7e262
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 648
  thumb_total_height: 324
- path: The Return of the Pink Panther.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=bbc7e262
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 648
  thumb_total_height: 324
