- path: Six Feet Under, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d545de89
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: The Wire, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=d545de89
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: Arrested Development.jpg
  width: 533
  height: 800
  thumb: thumbnails_0.jpg?crc=d545de89
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
- path: Frasier, Season 11.jpg
  width: 533
  height: 800
  thumb: thumbnails_0.jpg?crc=d545de89
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 864
  thumb_total_height: 324
