- path: Six Feet Under, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: The Wire, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Arrested Development.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Frasier, Season 11.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: The Animatrix.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Naruto, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Naruto, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: One Piece, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Stargate SG-1, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: 24, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: CSI Crime Scene Investigation, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: ER, Season 10.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Law & Order, Season 14.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: NCIS.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: The West Wing, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Samurai Jack, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: South Park, Season 7.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: The Office UK, Specials.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1520
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: The Simpsons, Season 15.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1740
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Angel, Season 5.jpg
  width: 604
  height: 800
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1956
  thumb_y: 324
  thumb_width: 244
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Smallville, Season 3.jpg
  width: 561
  height: 800
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_y: 648
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: All of Us.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 227
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Gilmore Girls, Season 4.jpg
  width: 1632
  height: 2193
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 443
  thumb_y: 648
  thumb_width: 241
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: NYPD Blue, Season 11.jpg
  width: 1000
  height: 1426
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 684
  thumb_y: 648
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Oz, Season 6.jpg
  width: 340
  height: 491
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 911
  thumb_y: 648
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Saturday Night Live, Season 29.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1135
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Sesame Street, Season 34.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1378
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: Sex and the City, Season 6.jpg
  width: 1000
  height: 1426
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1594
  thumb_y: 648
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
- path: The Shield, Season 2.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=522180af
  thumb_x: 1821
  thumb_y: 648
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2200
  thumb_total_height: 972
