- path: Adjudicator.jpg
  width: 286
  height: 285
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_y: 308
  thumb_width: 286
  thumb_height: 285
  thumb_total_width: 2980
  thumb_total_height: 593
- path: Berrada.jpg
  width: 308
  height: 308
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_x: 1232
  thumb_width: 308
  thumb_height: 308
  thumb_total_width: 2980
  thumb_total_height: 593
- path: Charon.jpg
  width: 286
  height: 287
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_x: 1836
  thumb_width: 286
  thumb_height: 287
  thumb_total_width: 2980
  thumb_total_height: 593
- path: Ernest.jpg
  width: 308
  height: 308
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_x: 616
  thumb_width: 308
  thumb_height: 308
  thumb_total_width: 2980
  thumb_total_height: 593
- path: John Wick.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_x: 2695
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2980
  thumb_total_height: 593
- path: Sofia.jpg
  width: 286
  height: 287
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_x: 2122
  thumb_width: 286
  thumb_height: 287
  thumb_total_width: 2980
  thumb_total_height: 593
- path: The Director.jpg
  width: 286
  height: 285
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_x: 571
  thumb_y: 308
  thumb_width: 286
  thumb_height: 285
  thumb_total_width: 2980
  thumb_total_height: 593
- path: The Doctor.jpg
  width: 308
  height: 308
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_x: 924
  thumb_width: 308
  thumb_height: 308
  thumb_total_width: 2980
  thumb_total_height: 593
- path: The Elder.jpg
  width: 308
  height: 308
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_x: 308
  thumb_width: 308
  thumb_height: 308
  thumb_total_width: 2980
  thumb_total_height: 593
- path: Tick Tock Man.jpg
  width: 308
  height: 308
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_width: 308
  thumb_height: 308
  thumb_total_width: 2980
  thumb_total_height: 593
- path: Winston.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_x: 286
  thumb_y: 308
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 2980
  thumb_total_height: 593
- path: Zero's Student 1.jpg
  width: 284
  height: 284
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_x: 857
  thumb_y: 308
  thumb_width: 284
  thumb_height: 284
  thumb_total_width: 2980
  thumb_total_height: 593
- path: Zero's Student 2.jpg
  width: 296
  height: 297
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_x: 1540
  thumb_width: 296
  thumb_height: 297
  thumb_total_width: 2980
  thumb_total_height: 593
- path: Zero.jpg
  width: 287
  height: 287
  thumb: thumbnails_0.jpg?crc=ffefcbce
  thumb_x: 2408
  thumb_width: 287
  thumb_height: 287
  thumb_total_width: 2980
  thumb_total_height: 593
