- path: The Andy Griffith Show.jpg
  width: 340
  height: 491
  thumb: thumbnails_0.jpg?crc=ac530fb1
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 1540
  thumb_total_height: 324
- path: Bonanza, Season 2.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=ac530fb1
  thumb_x: 224
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1540
  thumb_total_height: 324
- path: Gunsmoke, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=ac530fb1
  thumb_x: 444
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1540
  thumb_total_height: 324
- path: Perry Mason, Season 4.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=ac530fb1
  thumb_x: 660
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1540
  thumb_total_height: 324
- path: Alfred Hitchcock Presents, Season 6.jpg
  width: 800
  height: 1156
  thumb: thumbnails_0.jpg?crc=ac530fb1
  thumb_x: 880
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 1540
  thumb_total_height: 324
- path: The Untouchables, Season 2.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=ac530fb1
  thumb_x: 1104
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1540
  thumb_total_height: 324
- path: The Twilight Zone, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=ac530fb1
  thumb_x: 1324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1540
  thumb_total_height: 324
