- path: Succession, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: It's Always Sunny in Philadelphia, Season 16.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Ted Lasso, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Painkiller.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Scavengers Reign.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Silo Series.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Silo.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Star Trek Picard, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Star Trek Strange New Worlds, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: The Mandalorian, Season 3.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: What We Do in the Shadows, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Demon Slayer Kimetsu no Yaiba, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: For All Mankind, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Foundation, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Jujutsu Kaisen, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Mrs. Davis.jpg
  width: 474
  height: 711
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: One Piece, Season 22.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Scott Pilgrim Takes Off.jpeg
  width: 1400
  height: 1750
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: The Continental.jpeg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1771
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: The Last of Us.jpg
  width: 426
  height: 600
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1987
  thumb_y: 324
  thumb_width: 230
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Bob's Burgers, Season 14.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Archer, Season 14.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Family Guy, Season 22.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: South Park, Season 26.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: The Simpsons, Season 35.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 864
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Bel-Air, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1080
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Reservation Dogs, Season 3.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1296
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Saturday Night Live, Season 49.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1512
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Sesame Street, Season 54.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1755
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: The Crown, Season 6.jpg
  width: 1500
  height: 2100
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1971
  thumb_y: 648
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Yellowjackets, Season 2.jpg
  width: 1080
  height: 1350
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_y: 972
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: American Idol, Season 21.jpg
  width: 800
  height: 1000
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 259
  thumb_y: 972
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Big Brother, Season 25.jpg
  width: 800
  height: 877
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 518
  thumb_y: 972
  thumb_width: 295
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Project Runway, Season 20.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 813
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: RuPaul's Drag Race, Season 16.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1056
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Survivor, Season 44.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1272
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Survivor, Season 45.jpg
  width: 800
  height: 1000
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1515
  thumb_y: 972
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: The Amazing Race, Season 35.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1774
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: The Bachelor, Season 27.jpg
  width: 800
  height: 1000
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 1990
  thumb_y: 972
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
- path: Top Chef, Season 20.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=716ac014
  thumb_x: 2249
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2465
  thumb_total_height: 1296
