- path: Dungeons & Dragons Honor among thieves.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: John Wick Chapter 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Oppenheimer.jpg
  width: 1280
  height: 1920
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Poor Things.jpg
  width: 675
  height: 1000
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 648
  thumb_width: 218
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: The Holdovers.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 866
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Barbie.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1082
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Killers of the Flower Moon.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1298
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: La Chimera.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1514
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Luther The Fallen Sun.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1730
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Mars Express.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1946
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Mission Impossible Dead Reckoning.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: All of Us Strangers.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: American Fiction.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Anatomy of a Fall.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Aquaman and the Lost Kingdom.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Asteroid City.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Beau Is Afraid.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Blue Beetle.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Bottoms.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1728
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Christy.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Creed III.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Extraction 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Fast X.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Godzilla Minus One.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Insidious The Red Door.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 864
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: May December.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1080
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Past Lives.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1296
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Perfect Days.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1512
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Resident Evil Death Island.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1728
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Scream VI.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1944
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Sharper.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Shazam! Fury of the Gods.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 216
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Sing Sing.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 432
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: The Beast.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 648
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: The Boy and the Heron.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 864
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: The Flash.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1080
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: The Hunger Games The Ballad of Songbirds & Snakes.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1296
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: The Iron Claw.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1512
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: The Nun II.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1728
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: The Zone of Interest.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1944
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Transformers Rise of the Beasts.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Wonka.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 216
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Ant-Man and the Wasp Quantumania.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 432
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Expend4bles.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 648
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Guardians of the Galaxy Vol 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 864
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Missing.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1080
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: No One Will Save You.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1296
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: Spider-Man Across the Spider-Verse.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1512
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: The Covenant.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1728
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: The Equalizer 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=f10d0180
  thumb_x: 1944
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2162
  thumb_total_height: 1620
- path: The Marvels.jpg
  width: 800
  height: 1200
  thumb: thumbnails_1.jpg?crc=4f46889
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1080
  thumb_total_height: 324
- path: Demon Slayer Kimetsu no Yaiba To the Swordsmith Village.jpg
  width: 800
  height: 1200
  thumb: thumbnails_1.jpg?crc=4f46889
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1080
  thumb_total_height: 324
- path: Diary of a Wimpy Kid Christmas Cabin Fever.jpg
  width: 800
  height: 1200
  thumb: thumbnails_1.jpg?crc=4f46889
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1080
  thumb_total_height: 324
- path: Evil Dead Rise.jpg
  width: 800
  height: 1200
  thumb: thumbnails_1.jpg?crc=4f46889
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1080
  thumb_total_height: 324
- path: The Exorcist Believer.jpg
  width: 800
  height: 1200
  thumb: thumbnails_1.jpg?crc=4f46889
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1080
  thumb_total_height: 324
