- path: Dungeons & Dragons Honor among thieves.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.png?crc=b4ca5a59
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 216
  thumb_total_height: 324
