- path: Bereet.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Corpsman Dey.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Denarian Saal.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Drax the Destroyer.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Gamora.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Groot.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Horuz.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Korath the Pursuer.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Kraglin Obfonteri.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Meredith Quill.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Nebula.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Nova Prime.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 324
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Peter Quill _ Star-Lord.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 648
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Rocket Raccoon.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 972
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Ronan the Accuser.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: The Broker.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 1620
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: The Collector.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Yondu Udonta.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 2268
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Young Peter Quill.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=ec39a3c
  thumb_x: 2592
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
