- path: True Detective, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Curb Your Enthusiasm, Season 12.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: 3 Body Problem.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Avatar The Last Airbender.jpg
  width: 800
  height: 1199
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Bad Monkey.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Doctor Who, Season 1.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Fallout.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Silo, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Terminator Zero.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: The Boys, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: What We Do in the Shadows, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Demon Slayer Kimetsu no Yaiba, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: The Penguin.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Criminal Minds, Season 17.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Grey's Anatomy, Season 20.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Grey's Anatomy, Season 21.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Law & Order, Season 23.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Law & Order, Season 24.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: NCIS, Season 21.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1728
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: NCIS, Season 22.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Arcane, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Bob's Burgers, Season 15.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: The Simpsons, Season 36.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 432
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Bel-Air, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 648
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Abbott Elementary, Season 3.jpg
  width: 1080
  height: 1350
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 864
  thumb_y: 648
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Abbott Elementary, Season 4.jpg
  width: 1080
  height: 1350
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1123
  thumb_y: 648
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: House of the Dragon, Season 2.jpg
  width: 2025
  height: 3000
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1382
  thumb_y: 648
  thumb_width: 218
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Saturday Night Live, Season 50.jpg
  width: 852
  height: 1136
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1600
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Shogun.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1843
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Squid Game, Season 2.jpg
  width: 1200
  height: 1777
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 2059
  thumb_y: 648
  thumb_width: 219
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Chef's Table, Season 7.jpg
  width: 1587
  height: 2222
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_y: 972
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: The Jinx, Season 2.jpg
  width: 4050
  height: 6000
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 231
  thumb_y: 972
  thumb_width: 218
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: American Idol, Season 22.jpg
  width: 800
  height: 1000
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 449
  thumb_y: 972
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Big Brother, Season 26.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 708
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: RuPaul's Drag Race, Season 17.jpg
  width: 800
  height: 1000
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 924
  thumb_y: 972
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Survivor, Season 46.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1183
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Survivor, Season 47.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1426
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: The Amazing Race, Season 36.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1669
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: The Bachelor, Season 28.jpg
  width: 800
  height: 1000
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 1885
  thumb_y: 972
  thumb_width: 259
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Top Chef, Season 21.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_x: 2144
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
- path: Pachinko, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e58a95e9
  thumb_y: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2360
  thumb_total_height: 1620
