- path: Alan Stevens.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Alicia "Alice" Cabrera.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Benoit Blanc.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Detective Lieutenant Elliott.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Donna Thrombey.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Fran.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Harlan Thrombey.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Hugh Ransom Drysdale.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Jacob Thrombey.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Joni Thrombey.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Linda Drysdale.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Marta Cabrera.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 324
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Meg Thrombey.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 648
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Mr. Proofroc.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 972
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Richard Drysdale.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Trooper Wagner.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 1620
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Walt Thrombey.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Wanetta "Great Nana" Thrombey.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=f47a1875
  thumb_x: 2268
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
