- path: Baldur's Gate 3.jpg
  width: 1440
  height: 2160
  thumb: thumbnails_0.jpg?crc=4cdcc930
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 918
  thumb_total_height: 324
- path: Cyberpunk 2077 Phantom Liberty.jpeg
  width: 1200
  height: 1600
  thumb: thumbnails_0.jpg?crc=4cdcc930
  thumb_x: 216
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 918
  thumb_total_height: 324
- path: Alan Wake 2.jpg
  width: 1200
  height: 1600
  thumb: thumbnails_0.jpg?crc=4cdcc930
  thumb_x: 459
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 918
  thumb_total_height: 324
- path: Stray Gods.jpg
  width: 720
  height: 1080
  thumb: thumbnails_0.jpg?crc=4cdcc930
  thumb_x: 702
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 918
  thumb_total_height: 324
