- path: Band of Brothers.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Six Feet Under.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: The Sopranos, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Curb Your Enthusiasm, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Frasier, Season 9.jpg
  width: 576
  height: 864
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: One Piece, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: One Piece, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: One Piece, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Stargate SG-1, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: The X-Files, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: 24.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: CSI Crime Scene Investigation, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: ER, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Law & Order, Season 12.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: The West Wing, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Family Guy, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: Samurai Jack.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: South Park, Season 5.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: The Office UK.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 1736
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
- path: The Simpsons, Season 13.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=447ffe62
  thumb_x: 1952
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2168
  thumb_total_height: 648
