- path: General Ketheric Thorm.jpeg
  width: 532
  height: 532
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 1620
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Halsin.jpeg
  width: 620
  height: 620
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Jaheira.jpeg
  width: 663
  height: 663
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Minsc.jpeg
  width: 329
  height: 329
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Minthara.jpeg
  width: 496
  height: 496
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Mizora.jpeg
  width: 422
  height: 422
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Orin the Red.jpeg
  width: 1263
  height: 1263
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Bhaal.jpg
  width: 340
  height: 340
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Astarion.jpeg
  width: 532
  height: 532
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Gale.jpeg
  width: 477
  height: 477
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Karlach.jpeg
  width: 450
  height: 450
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Lae'zel.jpeg
  width: 494
  height: 494
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 324
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Shadowheart.jpeg
  width: 481
  height: 481
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 648
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Wyll.jpeg
  width: 471
  height: 471
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 972
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Lord Enver Gortash.jpeg
  width: 422
  height: 422
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Mystra.jpeg
  width: 253
  height: 253
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 2268
  thumb_y: 324
  thumb_width: 253
  thumb_height: 253
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Raphael.jpeg
  width: 446
  height: 446
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Volo.jpeg
  width: 363
  height: 363
  thumb: thumbnails_0.jpg?crc=97ca6969
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
