- path: Astarion.png
  width: 473
  height: 473
  thumb: thumbnails_0.png?crc=23c72da0
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3169
  thumb_total_height: 324
- path: Gale.png
  width: 419
  height: 419
  thumb: thumbnails_0.png?crc=23c72da0
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3169
  thumb_total_height: 324
- path: General Ketheric Thorm.jpeg
  width: 532
  height: 532
  thumb: thumbnails_0.jpg?crc=4f493cbb
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Halsin.jpeg
  width: 620
  height: 620
  thumb: thumbnails_0.jpg?crc=4f493cbb
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Jaheira.jpeg
  width: 663
  height: 663
  thumb: thumbnails_0.jpg?crc=4f493cbb
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Karlach.png
  width: 365
  height: 365
  thumb: thumbnails_0.png?crc=23c72da0
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3169
  thumb_total_height: 324
- path: Lae'zel.png
  width: 441
  height: 441
  thumb: thumbnails_0.png?crc=23c72da0
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3169
  thumb_total_height: 324
- path: Lord Enver Gortash.png
  width: 422
  height: 422
  thumb: thumbnails_0.png?crc=23c72da0
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3169
  thumb_total_height: 324
- path: Minsc.jpeg
  width: 329
  height: 329
  thumb: thumbnails_0.jpg?crc=4f493cbb
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Minthara.jpeg
  width: 496
  height: 496
  thumb: thumbnails_0.jpg?crc=4f493cbb
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Mizora.jpeg
  width: 422
  height: 422
  thumb: thumbnails_0.jpg?crc=4f493cbb
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Mystra.png
  width: 253
  height: 253
  thumb: thumbnails_0.png?crc=23c72da0
  thumb_x: 2916
  thumb_width: 253
  thumb_height: 253
  thumb_total_width: 3169
  thumb_total_height: 324
- path: Orin the Red.jpeg
  width: 1263
  height: 1263
  thumb: thumbnails_0.jpg?crc=4f493cbb
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Raphael.png
  width: 446
  height: 446
  thumb: thumbnails_0.png?crc=23c72da0
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3169
  thumb_total_height: 324
- path: Shadowheart.png
  width: 378
  height: 378
  thumb: thumbnails_0.png?crc=23c72da0
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3169
  thumb_total_height: 324
- path: Volo.png
  width: 363
  height: 363
  thumb: thumbnails_0.png?crc=23c72da0
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3169
  thumb_total_height: 324
- path: Wyll.png
  width: 415
  height: 415
  thumb: thumbnails_0.png?crc=23c72da0
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3169
  thumb_total_height: 324
- path: Bhaal.jpg
  width: 340
  height: 340
  thumb: thumbnails_0.jpg?crc=4f493cbb
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
