- path: Abram Tarasov.jpg
  width: 308
  height: 308
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_x: 1848
  thumb_width: 308
  thumb_height: 308
  thumb_total_width: 3015
  thumb_total_height: 593
- path: Ares.jpg
  width: 286
  height: 285
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_x: 571
  thumb_y: 308
  thumb_width: 286
  thumb_height: 285
  thumb_total_width: 3015
  thumb_total_height: 593
- path: Cassian.jpg
  width: 286
  height: 285
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_x: 285
  thumb_y: 308
  thumb_width: 286
  thumb_height: 285
  thumb_total_width: 3015
  thumb_total_height: 593
- path: Charon.jpg
  width: 286
  height: 287
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_x: 2729
  thumb_width: 286
  thumb_height: 287
  thumb_total_width: 3015
  thumb_total_height: 593
- path: Earl.jpg
  width: 308
  height: 308
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_x: 1232
  thumb_width: 308
  thumb_height: 308
  thumb_total_width: 3015
  thumb_total_height: 593
- path: Gianna D'Antonio.jpg
  width: 308
  height: 308
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_x: 1540
  thumb_width: 308
  thumb_height: 308
  thumb_total_width: 3015
  thumb_total_height: 593
- path: John Wick.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_y: 308
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 3015
  thumb_total_height: 593
- path: Julius.jpg
  width: 308
  height: 308
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_width: 308
  thumb_height: 308
  thumb_total_width: 3015
  thumb_total_height: 593
- path: Santino D'Antonio.jpg
  width: 287
  height: 287
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_x: 2442
  thumb_width: 287
  thumb_height: 287
  thumb_total_width: 3015
  thumb_total_height: 593
- path: Bowery King.jpg
  width: 286
  height: 287
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_x: 2156
  thumb_width: 286
  thumb_height: 287
  thumb_total_width: 3015
  thumb_total_height: 593
- path: The Cartographer.jpg
  width: 308
  height: 308
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_x: 924
  thumb_width: 308
  thumb_height: 308
  thumb_total_width: 3015
  thumb_total_height: 593
- path: The Sommelier.jpg
  width: 308
  height: 308
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_x: 616
  thumb_width: 308
  thumb_height: 308
  thumb_total_width: 3015
  thumb_total_height: 593
- path: The Tailor.jpg
  width: 308
  height: 308
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_x: 308
  thumb_width: 308
  thumb_height: 308
  thumb_total_width: 3015
  thumb_total_height: 593
- path: Winston.jpg
  width: 285
  height: 285
  thumb: thumbnails_0.jpg?crc=c2b29a64
  thumb_x: 857
  thumb_y: 308
  thumb_width: 285
  thumb_height: 285
  thumb_total_width: 3015
  thumb_total_height: 593
