- path: Andi Brand.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Benoit Blanc.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Birdie Jay.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Claire Debella.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Devon Debella.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Duke Cody.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Efficient Man.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Helen Brand.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Lionel Toussaint.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Ma.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Miles Bron.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Peg.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_x: 324
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Phillip.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_x: 648
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Whiskey.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=56af4ef5
  thumb_x: 972
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
