- path: Doctor Who, Season 16.jpg
  width: 1080
  height: 1620
  thumb: thumbnails_0.jpg?crc=4f5cdee
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2401
  thumb_total_height: 648
- path: Saturday Night Live, Season 4.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=4f5cdee
  thumb_x: 216
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2401
  thumb_total_height: 648
- path: Sesame Street, Season 10.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=4f5cdee
  thumb_x: 459
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2401
  thumb_total_height: 648
- path: Sesame Street, Season 11.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=4f5cdee
  thumb_x: 675
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2401
  thumb_total_height: 648
- path: The Jeffersons, Season 5.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=4f5cdee
  thumb_x: 891
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2401
  thumb_total_height: 648
- path: The Muppet Show, Season 3.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=4f5cdee
  thumb_x: 1111
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2401
  thumb_total_height: 648
- path: Dallas, Season 2.jpg
  width: 1590
  height: 1653
  thumb: thumbnails_0.jpg?crc=4f5cdee
  thumb_x: 1331
  thumb_width: 312
  thumb_height: 324
  thumb_total_width: 2401
  thumb_total_height: 648
- path: Dallas.jpg
  width: 1590
  height: 1653
  thumb: thumbnails_0.jpg?crc=4f5cdee
  thumb_x: 1643
  thumb_width: 312
  thumb_height: 324
  thumb_total_width: 2401
  thumb_total_height: 648
- path: Happy Days, Season 6.jpg
  width: 1065
  height: 1500
  thumb: thumbnails_0.jpg?crc=4f5cdee
  thumb_x: 1955
  thumb_width: 230
  thumb_height: 324
  thumb_total_width: 2401
  thumb_total_height: 648
- path: Barney Miller, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4f5cdee
  thumb_x: 2185
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2401
  thumb_total_height: 648
- path: Gilligan's Island, Season 4.jpg
  width: 800
  height: 1176
  thumb: thumbnails_0.jpg?crc=4f5cdee
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2401
  thumb_total_height: 648
- path: WKRP in Cincinnati.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=4f5cdee
  thumb_x: 220
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2401
  thumb_total_height: 648
