- path: Buford "Mad Dog" Tannen.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=a82ea2a0
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Chester the Bartender.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=a82ea2a0
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Clara Clayton.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=a82ea2a0
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Dr. Emmett "Doc" Brown.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=a82ea2a0
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Maggie McFly.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=a82ea2a0
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Marshall James Strickland.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=a82ea2a0
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Marty McFly.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=a82ea2a0
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
- path: Seamus McFly.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=a82ea2a0
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2592
  thumb_total_height: 324
