- path: Better Call Saul, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: The Americans, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Brooklyn Nine-Nine, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Curb Your Enthusiasm, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: It's Always Sunny in Philadelphia, Season 12.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 864
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Modern Family, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1080
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: All Hail King Julien Exiled.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1296
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Black Mirror, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1512
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Game of Thrones, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1728
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Legion.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1944
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Narcos, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Ozark.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Stranger Things, Season 2.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 432
  thumb_y: 324
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Attack on Titan, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 652
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: One Piece, Season 19.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 868
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Dark.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1084
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: The Expanse, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1300
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Twin Peaks, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1516
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Criminal Minds, Season 13.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1732
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Grey's Anatomy, Season 14.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1948
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Homeland, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: NCIS, Season 15.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 216
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Easy, Season 2.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 432
  thumb_y: 648
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Adventure Time, Season 10.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 652
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Adventure Time, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 868
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Archer, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1084
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: BoJack Horseman, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1300
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Bob's Burgers, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1516
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Family Guy, Season 16.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1732
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Samurai Jack, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1948
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: South Park, Season 21.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_y: 972
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Steven Universe, Season 5.jpg
  width: 720
  height: 1080
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 220
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: The Simpsons, Season 29.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 436
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Halt and Catch Fire, Season 4.jpg
  width: 544
  height: 800
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 652
  thumb_y: 972
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Mr. Robot, Season 3.jpg
  width: 561
  height: 800
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 872
  thumb_y: 972
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: Orphan Black, Season 5.jpg
  width: 553
  height: 800
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1099
  thumb_y: 972
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
- path: The Leftovers, Season 3.jpg
  width: 571
  height: 800
  thumb: thumbnails_0.jpg?crc=b2c2e037
  thumb_x: 1323
  thumb_y: 972
  thumb_width: 231
  thumb_height: 324
  thumb_total_width: 2164
  thumb_total_height: 1296
