- path: Deadwood, Season 3.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=e8151547
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 1084
  thumb_total_height: 324
- path: The Sopranos, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e8151547
  thumb_x: 220
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1084
  thumb_total_height: 324
- path: The Wire, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=e8151547
  thumb_x: 436
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1084
  thumb_total_height: 324
- path: 30 Rock.jpg
  width: 533
  height: 800
  thumb: thumbnails_0.jpg?crc=e8151547
  thumb_x: 652
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1084
  thumb_total_height: 324
- path: It's Always Sunny in Philadelphia, Season 2.jpg
  width: 533
  height: 800
  thumb: thumbnails_0.jpg?crc=e8151547
  thumb_x: 868
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 1084
  thumb_total_height: 324
