- path: Deadwood, Season 3.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: The Sopranos, Season 6.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 224
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: The Wire, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 440
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: 30 Rock.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 656
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: It's Always Sunny in Philadelphia, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 872
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Avatar The Last Airbender, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1088
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Dexter Series.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1304
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Dexter.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1520
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Death Note.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1736
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Naruto, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1952
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Naruto, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Battlestar Galactica, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 216
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Lost, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 432
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Stargate SG-1, Season 10.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 648
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: 24, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 864
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: CSI Crime Scene Investigation, Season 7.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1080
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Criminal Minds, Season 2.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1296
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: ER, Season 13.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1512
  thumb_y: 324
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Grey's Anatomy, Season 3.jpg
  width: 800
  height: 1141
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1728
  thumb_y: 324
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: House, Season 3.jpg
  width: 800
  height: 1137
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1955
  thumb_y: 324
  thumb_width: 228
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Law & Order, Season 17.jpg
  width: 500
  height: 750
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: NCIS, Season 4.jpg
  width: 800
  height: 1132
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 216
  thumb_y: 648
  thumb_width: 229
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Family Guy, Season 5.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 445
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: South Park, Season 10.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 661
  thumb_y: 648
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: The Office, Season 3.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 885
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: The Simpsons, Season 18.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1101
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Smallville, Season 6.jpg
  width: 561
  height: 800
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1317
  thumb_y: 648
  thumb_width: 227
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: All of Us, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1544
  thumb_y: 648
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Doctor Who, Season 2.jpg
  width: 250
  height: 337
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 1760
  thumb_y: 648
  thumb_width: 240
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Gilmore Girls, Season 7.jpg
  width: 1623
  height: 2214
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 2000
  thumb_y: 648
  thumb_width: 238
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Saturday Night Live, Season 32.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: Sesame Street, Season 37.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 243
  thumb_y: 972
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
- path: The Shield, Season 5.jpg
  width: 400
  height: 578
  thumb: thumbnails_0.jpg?crc=a04ad480
  thumb_x: 459
  thumb_y: 972
  thumb_width: 224
  thumb_height: 324
  thumb_total_width: 2238
  thumb_total_height: 1296
