- path: Andy Dufresne.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9dfb9743
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
- path: Brooks Hatlen.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9dfb9743
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
- path: Captain Byron Hadley.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9dfb9743
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
- path: Ellis Boyd "Red" Redding.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9dfb9743
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
- path: Heywood.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9dfb9743
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
- path: Tommy Williams.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9dfb9743
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
- path: Warden Samuel Norton.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9dfb9743
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 2268
  thumb_total_height: 324
