- path: Frasier, Season 4.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=966052dd
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 648
  thumb_total_height: 324
- path: Seinfeld, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=966052dd
  thumb_x: 216
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 648
  thumb_total_height: 324
- path: The X-Files, Season 4.jpg
  width: 600
  height: 900
  thumb: thumbnails_0.jpg?crc=966052dd
  thumb_x: 432
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 648
  thumb_total_height: 324
