name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: media

      - name: Run thumnbailer
        uses: alsosee/thumbnailer@main
        with:
          media: ./media
          r2_account_id: ${{ secrets.R2_ACCOUNT_ID }}
          r2_access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2_access_key_secret: ${{ secrets.R2_ACCESS_KEY_SECRET }}
          r2_bucket: media

      - name: Commit changes
        run: |
          cd media
          git config --global user.name "thumbnailer"
          git config --global user.email "thumbnailer@alsosee.info"
          git status --porcelain
          git add .
          git commit -m "Update thumbnails [skip ci]"
          git push

      - name: Trigger deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: alsosee/finder
          event-type: deploy
