name: pull

on:
  workflow_dispatch:
    inputs:
      path:
        description: Path to media to pull from R2, e.g. "Movies/2001/Harry Potter and the Philosopher's Stone/Characters/Harry Potter"
        required: true
  repository_dispatch:
    types: [pull]

permissions:
  contents: write

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: media

      - name: Set environment variables (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          echo "MEDIAPATH=${{ github.event.inputs.path }}" >> $GITHUB_ENV
          echo "DIRNAME=$(dirname "${{ github.event.inputs.path }}")" >> $GITHUB_ENV

      - name: Set environment variables (repository_dispatch)
        if: github.event_name == 'repository_dispatch'
        shell: bash
        run: |
          echo "MEDIAPATH=${{ github.event.client_payload.path }}" >> $GITHUB_ENV
          echo "DIRNAME=$(dirname "${{ github.event.client_payload.path }}")" >> $GITHUB_ENV

      - name: Download from R2
        uses: alsosee/r2action@main
        with:
          account_id: ${{ secrets.R2_ACCOUNT_ID }}
          access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
          access_key_secret: ${{ secrets.R2_ACCESS_KEY_SECRET }}
          bucket: media
          operation: get
          key: ${{ env.MEDIAPATH }}
          file: media/"${{ env.MEDIAPATH }}"

      # - name: Run thumnbailer
      #   uses: alsosee/thumbnailer@main
      #   with:
      #     media: ./media
      #     skip_image_upload: "true" # we don't need to upload images to R2, as they are already there
      #     r2_account_id: ${{ secrets.R2_ACCOUNT_ID }}
      #     r2_access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
      #     r2_access_key_secret: ${{ secrets.R2_ACCESS_KEY_SECRET }}
      #     r2_bucket: media

      - name: Commit changes
        id: changes
        run: |
          cd media
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 0
          fi

          # git config --global user.name "thumbnailer"
          # git config --global user.email "thumbnailer@alsosee.info"
          # git status --porcelain
          # git add .
          # git commit -m "Update thumbnails [skip ci]"
          # git push
          # echo "pushed=true" >> $GITHUB_OUTPUT

      # - name: Trigger deploy
      #   uses: peter-evans/repository-dispatch@v2
      #   if: steps.changes.outputs.pushed == 'true'
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     repository: alsosee/finder
      #     event-type: deploy
