# A new image was uploaded to R2, so we need to pull it and re-generate thumbnails.
# Workflow can be triggered manually or via repository_dispatch event (by CloudFlare Pages function).
# To minimize number of commits in main branch, this workflow creates a new branch, and commits changes there.
# Then it creates a pull request to merge changes from the new branch to main (if needed).
# Branch name is the same as the image path in R2, e.g. "Movies/2001/Harry Potter and the Philosopher's Stone/Characters".
name: pull

on:
  workflow_dispatch:
    inputs:
      path:
        description: Path to media to pull from R2, e.g. "Movies/2001/Harry Potter and the Philosopher's Stone/Characters/Harry Potter"
        required: true
  repository_dispatch:
    types: [pull]

permissions:
  contents: write

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: media

      - name: Set environment variables (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: echo "MEDIAPATH=${{ github.event.inputs.path }}" >> $GITHUB_ENV

      - name: Set environment variables (repository_dispatch)
        if: github.event_name == 'repository_dispatch'
        shell: bash
        run: echo "MEDIAPATH=${{ github.event.client_payload.path }}" >> $GITHUB_ENV

      - name: Set environment variables
        shell: bash
        run: |
          echo "DIRNAME=$(dirname "$MEDIAPATH")" >> $GITHUB_ENV
          echo "BRANCHNAME=$(dirname "$MEDIAPATH" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr '~^:' '-' | sed "s/'/-/g")" >> $GITHUB_ENV

      - name: Download from R2
        uses: alsosee/r2action@main
        with:
          account_id: ${{ secrets.R2_ACCOUNT_ID }}
          access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
          access_key_secret: ${{ secrets.R2_ACCESS_KEY_SECRET }}
          bucket: media
          operation: get
          key: ${{ env.MEDIAPATH }}
          file: media/${{ env.MEDIAPATH }}

      - name: Create branch
        run: |
          cd media
          git config --global user.name 'GitHub Actions (pull workflow)'
          git config --global user.email 'gha@alsosee.info'
          git checkout -b $BRANCHNAME
          git add "$MEDIAPATH"
          git commit -m "Pull $MEDIAPATH"
          git push origin $BRANCHNAME

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Pull $MEDIAPATH"
          path: media
          branch: $BRANCHNAME
          title: "Pull $DIRNAME"
          body: "Pull $DIRNAME"
          delete-branch: true
