- path: Cheers, Season 7.jpg
  width: 490
  height: 738
  thumb: thumbnails_0.jpg?crc=2a95fa23
  thumb_width: 215
  thumb_height: 324
  thumb_total_width: 2197
  thumb_total_height: 324
- path: Dragon Ball, Season 8.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=2a95fa23
  thumb_x: 215
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2197
  thumb_total_height: 324
- path: Dragon Ball, Season 9.jpg
  width: 800
  height: 1200
  thumb: thumbnails_0.jpg?crc=2a95fa23
  thumb_x: 431
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2197
  thumb_total_height: 324
- path: Doctor Who, Season 25.jpg
  width: 1080
  height: 1620
  thumb: thumbnails_0.jpg?crc=2a95fa23
  thumb_x: 647
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2197
  thumb_total_height: 324
- path: Mister Rogers' Neighborhood, Season 19.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=2a95fa23
  thumb_x: 863
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2197
  thumb_total_height: 324
- path: Roseanne.jpg
  width: 1383
  height: 2048
  thumb: thumbnails_0.jpg?crc=2a95fa23
  thumb_x: 1083
  thumb_width: 219
  thumb_height: 324
  thumb_total_width: 2197
  thumb_total_height: 324
- path: Saturday Night Live, Season 14.jpg
  width: 2160
  height: 2880
  thumb: thumbnails_0.jpg?crc=2a95fa23
  thumb_x: 1302
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2197
  thumb_total_height: 324
- path: Sesame Street, Season 20.jpg
  width: 2000
  height: 3000
  thumb: thumbnails_0.jpg?crc=2a95fa23
  thumb_x: 1545
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2197
  thumb_total_height: 324
- path: The Cosby Show, Season 5.jpg
  width: 680
  height: 1000
  thumb: thumbnails_0.jpg?crc=2a95fa23
  thumb_x: 1761
  thumb_width: 220
  thumb_height: 324
  thumb_total_width: 2197
  thumb_total_height: 324
- path: The Golden Girls, Season 4.jpg
  width: 1000
  height: 1500
  thumb: thumbnails_0.jpg?crc=2a95fa23
  thumb_x: 1981
  thumb_width: 216
  thumb_height: 324
  thumb_total_width: 2197
  thumb_total_height: 324
