- path: A Way Out.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Assassin's Creed Odyssey.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 243
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Assassin's Creed Rebellion.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 486
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Celeste.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 729
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Command & Conquer Rivals.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Detroit Become Human.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 1215
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Fable Fortune.jpg
  width: 800
  height: 1077
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 1458
  thumb_width: 240
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Forza Horizon 4.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 1698
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Friday the 13th Killer Puzzle.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 1941
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: God of War.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 2184
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Gris.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Gwent The Witcher Card Game.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 243
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Hotel Transylvania 3 Monsters Overboard.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 486
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Jurassic World Alive.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 729
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Jurassic World Evolution.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 972
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Prince of Persia Escape.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 1215
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Red Dead Redemption 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 1458
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Shadow of the Tomb Raider.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 1701
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Tetris Effect.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 1944
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: This Is the Police 2.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 2187
  thumb_y: 324
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Thronebreaker The Witcher Tales.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Tomb Raider Arcade.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 243
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: World of Warcraft Battle for Azeroth.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 486
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Zarvot.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 729
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: ZeroRanger.jpg
  width: 800
  height: 1067
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 972
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Among Us.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 1215
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Dead Cells.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 1458
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Return of the Obra Dinn.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 1701
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: RimWorld.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 1944
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Subnautica.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 2187
  thumb_y: 648
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Super Smash Bros. Ultimate.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Dragon Ball FighterZ.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 243
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
- path: Sea of Thieves.jpg
  width: 800
  height: 1066
  thumb: thumbnails_0.jpg?crc=45a1fa47
  thumb_x: 486
  thumb_y: 972
  thumb_width: 243
  thumb_height: 324
  thumb_total_width: 2430
  thumb_total_height: 1296
