- path: Baron Vladimir Harkonnen.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9f4b13a3
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Beast Rabban.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9f4b13a3
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Chani.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9f4b13a3
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Emperor Shaddam IV.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9f4b13a3
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Feyd-Rautha Harkonnen.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9f4b13a3
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Gurney Halleck.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9f4b13a3
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Lady Jessica.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9f4b13a3
  thumb_x: 1944
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Lady Margot Fenring.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9f4b13a3
  thumb_x: 2268
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Paul Atreides.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9f4b13a3
  thumb_x: 2592
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Princess Irulan.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9f4b13a3
  thumb_x: 2916
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
- path: Stilgar.jpg
  width: 400
  height: 400
  thumb: thumbnails_0.jpg?crc=9f4b13a3
  thumb_y: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 3240
  thumb_total_height: 648
